/*---------------------------------------------------------------------------
 * This file is autogenerated file using huawei LCD parser. Please do not edit it.
 * Update input XML file to add a new entry or update variable in this file
 * Parser location: vendor/huawei/chipset_common/devkit/lcdkit/tools 
 *---------------------------------------------------------------------------*/

#ifndef _LCDKIT_EFFECT__H_
#define _LCDKIT_EFFECT__H_


#include "victoria_va_jdi_nt35696_5p5_1080p_cmd.h"

#include "victoria_va_sharp_td4322_5p5_1080p_cmd.h"

#include "victoria_va_lgd_nt36772_5p5_1080p_cmd.h"

#include "victoria_va_jdi_nt35696h_5p1_1080p_cmd.h"

#include "victoria_va_tianma_td4322_5p5_1080p_cmd.h"

#include "default_auo_otm1901a_5p2_1080p_video_default.h"

#include "vicky_va_jdi_s6d1ha2_5p5_2k_cmd.h"

#include "vicky_va_jdi_otm2503b_5p5_2k_cmd.h"

#include "stf_jdi_r63452_5p2_1080p_cmd.h"

#include "stf_lg_r69006_5p2_1080p_cmd.h"

#include "stf_sharp_nt35695_5p2_1080p_cmd.h"

#include "bac_tianma_td4310_5p5_1080p_video.h"

#include "stf_tianma_td4310_5p2_1080p_video.h"

#include "bac_auo_nt36672_5p5_1080p_video.h"

#include "stf_v3_lg_r69006_5p2_1080p_cmd.h"

#include "stf_v3_jdi_r63452_5p2_1080p_cmd.h"

#include "stf_v3_sharp_nt35695_5p2_1080p_cmd.h"

#include "stf_v3_tianma_td4310_5p2_1080p_video.h"

/*---------------------------------------------------------------------------*/
/* static panel selection variable                                           */
/*---------------------------------------------------------------------------*/
enum {
VICTORIA_VA_JDI_NT35696_5P5_1080P_CMD_PANEL,
VICTORIA_VA_SHARP_TD4322_5P5_1080P_CMD_PANEL,
VICTORIA_VA_LGD_NT36772_5P5_1080P_CMD_PANEL,
VICTORIA_VA_JDI_NT35696H_5P1_1080P_CMD_PANEL,
VICTORIA_VA_TIANMA_TD4322_5P5_1080P_CMD_PANEL,
DEFAULT_AUO_OTM1901A_5P2_1080P_VIDEO_DEFAULT_PANEL,
VICKY_VA_JDI_S6D1HA2_5P5_2K_CMD_PANEL,
VICKY_VA_JDI_OTM2503B_5P5_2K_CMD_PANEL,
STF_JDI_R63452_5P2_1080P_CMD_PANEL,
STF_LG_R69006_5P2_1080P_CMD_PANEL,
STF_SHARP_NT35695_5P2_1080P_CMD_PANEL,
BAC_TIANMA_TD4310_5P5_1080P_VIDEO_PANEL,
STF_TIANMA_TD4310_5P2_1080P_VIDEO_PANEL,
BAC_AUO_NT36672_5P5_1080P_VIDEO_PANEL,
STF_V3_LG_R69006_5P2_1080P_CMD_PANEL,
STF_V3_JDI_R63452_5P2_1080P_CMD_PANEL,
STF_V3_SHARP_NT35695_5P2_1080P_CMD_PANEL,
STF_V3_TIANMA_TD4310_5P2_1080P_VIDEO_PANEL,
INVALID_PANEL_ID,
};


/*---------------------------------------------------------------------------*/
/* static panel board mapping variable                                           */
/*---------------------------------------------------------------------------*/
struct lcdkit_board_map {
    uint8_t lcd_id;
    char *panel_compatible;
    uint32_t product_id;
};

static struct lcdkit_board_map lcdkit_map[] = {
    {VICTORIA_VA_JDI_NT35696_5P5_1080P_CMD_PANEL, "jdi_nt35696_5p1_1080P_cmd", 1000},
    {VICTORIA_VA_SHARP_TD4322_5P5_1080P_CMD_PANEL, "sharp_td4322_5p1_1080P_cmd", 1000},
    {VICTORIA_VA_LGD_NT36772_5P5_1080P_CMD_PANEL, "lgd_nt36772_5p1_1080P_cmd", 1000},
    {VICTORIA_VA_JDI_NT35696H_5P1_1080P_CMD_PANEL, "jdi_nt35696h_5p1_1080P_cmd", 1000},
    {VICTORIA_VA_TIANMA_TD4322_5P5_1080P_CMD_PANEL, "tianma_td4322_5p1_1080P_cmd", 1000},
    {DEFAULT_AUO_OTM1901A_5P2_1080P_VIDEO_DEFAULT_PANEL, "auo_otm1901a_5p2_1080p_video_default", 0},
    {VICKY_VA_JDI_S6D1HA2_5P5_2K_CMD_PANEL, "jdi_s6d1ha2_5p5_2k_cmd", 2100},
    {VICKY_VA_JDI_OTM2503B_5P5_2K_CMD_PANEL, "jdi_otm2503b_5p5_2k_cmd", 2000},
    {STF_JDI_R63452_5P2_1080P_CMD_PANEL, "jdi_r63452_5p2_1080P_cmd", 3000},
    {STF_LG_R69006_5P2_1080P_CMD_PANEL, "lg_r69006_5p2_1080P_cmd", 3000},
    {STF_SHARP_NT35695_5P2_1080P_CMD_PANEL, "sharp_nt35695_5p2_1080P_cmd", 3000},
    {BAC_TIANMA_TD4310_5P5_1080P_VIDEO_PANEL, "tianma_td4310_5p5_1080p_video", 4000},
    {STF_TIANMA_TD4310_5P2_1080P_VIDEO_PANEL, "tianma_td4310_5p2_1080p_video", 3000},
    {BAC_AUO_NT36672_5P5_1080P_VIDEO_PANEL, "auo_nt36672_5p5_1080p_video", 4000},
    {STF_V3_LG_R69006_5P2_1080P_CMD_PANEL, "lg_r69006_5p2_1080P_cmd", 3001},
    {STF_V3_JDI_R63452_5P2_1080P_CMD_PANEL, "jdi_r63452_5p2_1080P_cmd", 3001},
    {STF_V3_SHARP_NT35695_5P2_1080P_CMD_PANEL, "sharp_nt35695_5p2_1080P_cmd", 3001},
    {STF_V3_TIANMA_TD4310_5P2_1080P_VIDEO_PANEL, "tianma_td4310_5p2_1080p_video", 3001},
};

static void lcdkit_effect_get_data(uint8_t panel_id, struct hisi_panel_info* pinfo)
{
    switch (panel_id) {
    case VICTORIA_VA_JDI_NT35696_5P5_1080P_CMD_PANEL:
        if (pinfo->acm_support == 1)
        {
            pinfo->acm_lut_hue_table = victoria_va_jdi_nt35696_5p5_1080p_cmd_acm_lut_hue_table;
            pinfo->acm_lut_hue_table_len = ARRAY_SIZE(victoria_va_jdi_nt35696_5p5_1080p_cmd_acm_lut_hue_table);
            pinfo->acm_lut_sata_table = victoria_va_jdi_nt35696_5p5_1080p_cmd_acm_lut_sata_table;
            pinfo->acm_lut_sata_table_len = ARRAY_SIZE(victoria_va_jdi_nt35696_5p5_1080p_cmd_acm_lut_sata_table);
            pinfo->acm_lut_satr_table = victoria_va_jdi_nt35696_5p5_1080p_cmd_acm_lut_satr_table;
            pinfo->acm_lut_satr_table_len = ARRAY_SIZE(victoria_va_jdi_nt35696_5p5_1080p_cmd_acm_lut_satr_table);
            pinfo->acm_lut_satr0_table = victoria_va_jdi_nt35696_5p5_1080p_cmd_acm_lut_satr0_table;
            pinfo->acm_lut_satr0_table_len = ARRAY_SIZE(victoria_va_jdi_nt35696_5p5_1080p_cmd_acm_lut_satr0_table);
            pinfo->acm_lut_satr1_table = victoria_va_jdi_nt35696_5p5_1080p_cmd_acm_lut_satr1_table;
            pinfo->acm_lut_satr1_table_len = ARRAY_SIZE(victoria_va_jdi_nt35696_5p5_1080p_cmd_acm_lut_satr1_table);
            pinfo->acm_lut_satr2_table = victoria_va_jdi_nt35696_5p5_1080p_cmd_acm_lut_satr2_table;
            pinfo->acm_lut_satr2_table_len = ARRAY_SIZE(victoria_va_jdi_nt35696_5p5_1080p_cmd_acm_lut_satr2_table);
            pinfo->acm_lut_satr3_table = victoria_va_jdi_nt35696_5p5_1080p_cmd_acm_lut_satr3_table;
            pinfo->acm_lut_satr3_table_len = ARRAY_SIZE(victoria_va_jdi_nt35696_5p5_1080p_cmd_acm_lut_satr3_table);
            pinfo->acm_lut_satr4_table = victoria_va_jdi_nt35696_5p5_1080p_cmd_acm_lut_satr4_table;
            pinfo->acm_lut_satr4_table_len = ARRAY_SIZE(victoria_va_jdi_nt35696_5p5_1080p_cmd_acm_lut_satr4_table);
            pinfo->acm_lut_satr5_table = victoria_va_jdi_nt35696_5p5_1080p_cmd_acm_lut_satr5_table;
            pinfo->acm_lut_satr5_table_len = ARRAY_SIZE(victoria_va_jdi_nt35696_5p5_1080p_cmd_acm_lut_satr5_table);
            pinfo->acm_lut_satr6_table = victoria_va_jdi_nt35696_5p5_1080p_cmd_acm_lut_satr6_table;
            pinfo->acm_lut_satr6_table_len = ARRAY_SIZE(victoria_va_jdi_nt35696_5p5_1080p_cmd_acm_lut_satr6_table);
            pinfo->acm_lut_satr7_table = victoria_va_jdi_nt35696_5p5_1080p_cmd_acm_lut_satr7_table;
            pinfo->acm_lut_satr7_table_len = ARRAY_SIZE(victoria_va_jdi_nt35696_5p5_1080p_cmd_acm_lut_satr7_table);
            pinfo->video_acm_lut_hue_table = victoria_va_jdi_nt35696_5p5_1080p_cmd_video_acm_lut_hue_table;
            pinfo->video_acm_lut_sata_table = victoria_va_jdi_nt35696_5p5_1080p_cmd_video_acm_lut_sata_table;
            pinfo->video_acm_lut_satr0_table = victoria_va_jdi_nt35696_5p5_1080p_cmd_video_acm_lut_satr0_table;
            pinfo->video_acm_lut_satr1_table = victoria_va_jdi_nt35696_5p5_1080p_cmd_video_acm_lut_satr1_table;
            pinfo->video_acm_lut_satr2_table = victoria_va_jdi_nt35696_5p5_1080p_cmd_video_acm_lut_satr2_table;
            pinfo->video_acm_lut_satr3_table = victoria_va_jdi_nt35696_5p5_1080p_cmd_video_acm_lut_satr3_table;
            pinfo->video_acm_lut_satr4_table = victoria_va_jdi_nt35696_5p5_1080p_cmd_video_acm_lut_satr4_table;
            pinfo->video_acm_lut_satr5_table = victoria_va_jdi_nt35696_5p5_1080p_cmd_video_acm_lut_satr5_table;
            pinfo->video_acm_lut_satr6_table = victoria_va_jdi_nt35696_5p5_1080p_cmd_video_acm_lut_satr6_table;
            pinfo->video_acm_lut_satr7_table = victoria_va_jdi_nt35696_5p5_1080p_cmd_video_acm_lut_satr7_table;
        }
        if (pinfo->gamma_support == 1)
        {
            pinfo->gamma_lut_table_R = victoria_va_jdi_nt35696_5p5_1080p_cmd_gamma_lut_table_R;
            pinfo->gamma_lut_table_G = victoria_va_jdi_nt35696_5p5_1080p_cmd_gamma_lut_table_G;
            pinfo->gamma_lut_table_B = victoria_va_jdi_nt35696_5p5_1080p_cmd_gamma_lut_table_B;
            pinfo->gamma_lut_table_len = ARRAY_SIZE(victoria_va_jdi_nt35696_5p5_1080p_cmd_gamma_lut_table_R);
            pinfo->igm_lut_table_R = victoria_va_jdi_nt35696_5p5_1080p_cmd_igm_lut_table_R;
            pinfo->igm_lut_table_G = victoria_va_jdi_nt35696_5p5_1080p_cmd_igm_lut_table_G;
            pinfo->igm_lut_table_B = victoria_va_jdi_nt35696_5p5_1080p_cmd_igm_lut_table_B;
            pinfo->igm_lut_table_len = ARRAY_SIZE(victoria_va_jdi_nt35696_5p5_1080p_cmd_igm_lut_table_R);
            pinfo->gmp_lut_table_low32bit = &victoria_va_jdi_nt35696_5p5_1080p_cmd_gmp_lut_table_low32bit[0][0][0];
            pinfo->gmp_lut_table_high4bit = &victoria_va_jdi_nt35696_5p5_1080p_cmd_gmp_lut_table_high4bit[0][0][0];
            pinfo->gmp_lut_table_len = ARRAY_SIZE(victoria_va_jdi_nt35696_5p5_1080p_cmd_gmp_lut_table_low32bit);
            pinfo->xcc_table = victoria_va_jdi_nt35696_5p5_1080p_cmd_xcc_table;
            pinfo->xcc_table_len = ARRAY_SIZE(victoria_va_jdi_nt35696_5p5_1080p_cmd_xcc_table);
        }
        break;
    case VICTORIA_VA_SHARP_TD4322_5P5_1080P_CMD_PANEL:
        if (pinfo->acm_support == 1)
        {
            pinfo->acm_lut_hue_table = victoria_va_sharp_td4322_5p5_1080p_cmd_acm_lut_hue_table;
            pinfo->acm_lut_hue_table_len = ARRAY_SIZE(victoria_va_sharp_td4322_5p5_1080p_cmd_acm_lut_hue_table);
            pinfo->acm_lut_sata_table = victoria_va_sharp_td4322_5p5_1080p_cmd_acm_lut_sata_table;
            pinfo->acm_lut_sata_table_len = ARRAY_SIZE(victoria_va_sharp_td4322_5p5_1080p_cmd_acm_lut_sata_table);
            pinfo->acm_lut_satr_table = victoria_va_sharp_td4322_5p5_1080p_cmd_acm_lut_satr_table;
            pinfo->acm_lut_satr_table_len = ARRAY_SIZE(victoria_va_sharp_td4322_5p5_1080p_cmd_acm_lut_satr_table);
            pinfo->acm_lut_satr0_table = victoria_va_sharp_td4322_5p5_1080p_cmd_acm_lut_satr0_table;
            pinfo->acm_lut_satr0_table_len = ARRAY_SIZE(victoria_va_sharp_td4322_5p5_1080p_cmd_acm_lut_satr0_table);
            pinfo->acm_lut_satr1_table = victoria_va_sharp_td4322_5p5_1080p_cmd_acm_lut_satr1_table;
            pinfo->acm_lut_satr1_table_len = ARRAY_SIZE(victoria_va_sharp_td4322_5p5_1080p_cmd_acm_lut_satr1_table);
            pinfo->acm_lut_satr2_table = victoria_va_sharp_td4322_5p5_1080p_cmd_acm_lut_satr2_table;
            pinfo->acm_lut_satr2_table_len = ARRAY_SIZE(victoria_va_sharp_td4322_5p5_1080p_cmd_acm_lut_satr2_table);
            pinfo->acm_lut_satr3_table = victoria_va_sharp_td4322_5p5_1080p_cmd_acm_lut_satr3_table;
            pinfo->acm_lut_satr3_table_len = ARRAY_SIZE(victoria_va_sharp_td4322_5p5_1080p_cmd_acm_lut_satr3_table);
            pinfo->acm_lut_satr4_table = victoria_va_sharp_td4322_5p5_1080p_cmd_acm_lut_satr4_table;
            pinfo->acm_lut_satr4_table_len = ARRAY_SIZE(victoria_va_sharp_td4322_5p5_1080p_cmd_acm_lut_satr4_table);
            pinfo->acm_lut_satr5_table = victoria_va_sharp_td4322_5p5_1080p_cmd_acm_lut_satr5_table;
            pinfo->acm_lut_satr5_table_len = ARRAY_SIZE(victoria_va_sharp_td4322_5p5_1080p_cmd_acm_lut_satr5_table);
            pinfo->acm_lut_satr6_table = victoria_va_sharp_td4322_5p5_1080p_cmd_acm_lut_satr6_table;
            pinfo->acm_lut_satr6_table_len = ARRAY_SIZE(victoria_va_sharp_td4322_5p5_1080p_cmd_acm_lut_satr6_table);
            pinfo->acm_lut_satr7_table = victoria_va_sharp_td4322_5p5_1080p_cmd_acm_lut_satr7_table;
            pinfo->acm_lut_satr7_table_len = ARRAY_SIZE(victoria_va_sharp_td4322_5p5_1080p_cmd_acm_lut_satr7_table);
            pinfo->video_acm_lut_hue_table = victoria_va_sharp_td4322_5p5_1080p_cmd_video_acm_lut_hue_table;
            pinfo->video_acm_lut_sata_table = victoria_va_sharp_td4322_5p5_1080p_cmd_video_acm_lut_sata_table;
            pinfo->video_acm_lut_satr0_table = victoria_va_sharp_td4322_5p5_1080p_cmd_video_acm_lut_satr0_table;
            pinfo->video_acm_lut_satr1_table = victoria_va_sharp_td4322_5p5_1080p_cmd_video_acm_lut_satr1_table;
            pinfo->video_acm_lut_satr2_table = victoria_va_sharp_td4322_5p5_1080p_cmd_video_acm_lut_satr2_table;
            pinfo->video_acm_lut_satr3_table = victoria_va_sharp_td4322_5p5_1080p_cmd_video_acm_lut_satr3_table;
            pinfo->video_acm_lut_satr4_table = victoria_va_sharp_td4322_5p5_1080p_cmd_video_acm_lut_satr4_table;
            pinfo->video_acm_lut_satr5_table = victoria_va_sharp_td4322_5p5_1080p_cmd_video_acm_lut_satr5_table;
            pinfo->video_acm_lut_satr6_table = victoria_va_sharp_td4322_5p5_1080p_cmd_video_acm_lut_satr6_table;
            pinfo->video_acm_lut_satr7_table = victoria_va_sharp_td4322_5p5_1080p_cmd_video_acm_lut_satr7_table;
        }
        if (pinfo->gamma_support == 1)
        {
            pinfo->gamma_lut_table_R = victoria_va_sharp_td4322_5p5_1080p_cmd_gamma_lut_table_R;
            pinfo->gamma_lut_table_G = victoria_va_sharp_td4322_5p5_1080p_cmd_gamma_lut_table_G;
            pinfo->gamma_lut_table_B = victoria_va_sharp_td4322_5p5_1080p_cmd_gamma_lut_table_B;
            pinfo->gamma_lut_table_len = ARRAY_SIZE(victoria_va_sharp_td4322_5p5_1080p_cmd_gamma_lut_table_R);
            pinfo->igm_lut_table_R = victoria_va_sharp_td4322_5p5_1080p_cmd_igm_lut_table_R;
            pinfo->igm_lut_table_G = victoria_va_sharp_td4322_5p5_1080p_cmd_igm_lut_table_G;
            pinfo->igm_lut_table_B = victoria_va_sharp_td4322_5p5_1080p_cmd_igm_lut_table_B;
            pinfo->igm_lut_table_len = ARRAY_SIZE(victoria_va_sharp_td4322_5p5_1080p_cmd_igm_lut_table_R);
            pinfo->gmp_lut_table_low32bit = &victoria_va_sharp_td4322_5p5_1080p_cmd_gmp_lut_table_low32bit[0][0][0];
            pinfo->gmp_lut_table_high4bit = &victoria_va_sharp_td4322_5p5_1080p_cmd_gmp_lut_table_high4bit[0][0][0];
            pinfo->gmp_lut_table_len = ARRAY_SIZE(victoria_va_sharp_td4322_5p5_1080p_cmd_gmp_lut_table_low32bit);
            pinfo->xcc_table = victoria_va_sharp_td4322_5p5_1080p_cmd_xcc_table;
            pinfo->xcc_table_len = ARRAY_SIZE(victoria_va_sharp_td4322_5p5_1080p_cmd_xcc_table);
        }
        break;
    case VICTORIA_VA_LGD_NT36772_5P5_1080P_CMD_PANEL:
        if (pinfo->acm_support == 1)
        {
            pinfo->acm_lut_hue_table = victoria_va_lgd_nt36772_5p5_1080p_cmd_acm_lut_hue_table;
            pinfo->acm_lut_hue_table_len = ARRAY_SIZE(victoria_va_lgd_nt36772_5p5_1080p_cmd_acm_lut_hue_table);
            pinfo->acm_lut_sata_table = victoria_va_lgd_nt36772_5p5_1080p_cmd_acm_lut_sata_table;
            pinfo->acm_lut_sata_table_len = ARRAY_SIZE(victoria_va_lgd_nt36772_5p5_1080p_cmd_acm_lut_sata_table);
            pinfo->acm_lut_satr_table = victoria_va_lgd_nt36772_5p5_1080p_cmd_acm_lut_satr_table;
            pinfo->acm_lut_satr_table_len = ARRAY_SIZE(victoria_va_lgd_nt36772_5p5_1080p_cmd_acm_lut_satr_table);
            pinfo->acm_lut_satr0_table = victoria_va_lgd_nt36772_5p5_1080p_cmd_acm_lut_satr0_table;
            pinfo->acm_lut_satr0_table_len = ARRAY_SIZE(victoria_va_lgd_nt36772_5p5_1080p_cmd_acm_lut_satr0_table);
            pinfo->acm_lut_satr1_table = victoria_va_lgd_nt36772_5p5_1080p_cmd_acm_lut_satr1_table;
            pinfo->acm_lut_satr1_table_len = ARRAY_SIZE(victoria_va_lgd_nt36772_5p5_1080p_cmd_acm_lut_satr1_table);
            pinfo->acm_lut_satr2_table = victoria_va_lgd_nt36772_5p5_1080p_cmd_acm_lut_satr2_table;
            pinfo->acm_lut_satr2_table_len = ARRAY_SIZE(victoria_va_lgd_nt36772_5p5_1080p_cmd_acm_lut_satr2_table);
            pinfo->acm_lut_satr3_table = victoria_va_lgd_nt36772_5p5_1080p_cmd_acm_lut_satr3_table;
            pinfo->acm_lut_satr3_table_len = ARRAY_SIZE(victoria_va_lgd_nt36772_5p5_1080p_cmd_acm_lut_satr3_table);
            pinfo->acm_lut_satr4_table = victoria_va_lgd_nt36772_5p5_1080p_cmd_acm_lut_satr4_table;
            pinfo->acm_lut_satr4_table_len = ARRAY_SIZE(victoria_va_lgd_nt36772_5p5_1080p_cmd_acm_lut_satr4_table);
            pinfo->acm_lut_satr5_table = victoria_va_lgd_nt36772_5p5_1080p_cmd_acm_lut_satr5_table;
            pinfo->acm_lut_satr5_table_len = ARRAY_SIZE(victoria_va_lgd_nt36772_5p5_1080p_cmd_acm_lut_satr5_table);
            pinfo->acm_lut_satr6_table = victoria_va_lgd_nt36772_5p5_1080p_cmd_acm_lut_satr6_table;
            pinfo->acm_lut_satr6_table_len = ARRAY_SIZE(victoria_va_lgd_nt36772_5p5_1080p_cmd_acm_lut_satr6_table);
            pinfo->acm_lut_satr7_table = victoria_va_lgd_nt36772_5p5_1080p_cmd_acm_lut_satr7_table;
            pinfo->acm_lut_satr7_table_len = ARRAY_SIZE(victoria_va_lgd_nt36772_5p5_1080p_cmd_acm_lut_satr7_table);
            pinfo->video_acm_lut_hue_table = victoria_va_lgd_nt36772_5p5_1080p_cmd_video_acm_lut_hue_table;
            pinfo->video_acm_lut_sata_table = victoria_va_lgd_nt36772_5p5_1080p_cmd_video_acm_lut_sata_table;
            pinfo->video_acm_lut_satr0_table = victoria_va_lgd_nt36772_5p5_1080p_cmd_video_acm_lut_satr0_table;
            pinfo->video_acm_lut_satr1_table = victoria_va_lgd_nt36772_5p5_1080p_cmd_video_acm_lut_satr1_table;
            pinfo->video_acm_lut_satr2_table = victoria_va_lgd_nt36772_5p5_1080p_cmd_video_acm_lut_satr2_table;
            pinfo->video_acm_lut_satr3_table = victoria_va_lgd_nt36772_5p5_1080p_cmd_video_acm_lut_satr3_table;
            pinfo->video_acm_lut_satr4_table = victoria_va_lgd_nt36772_5p5_1080p_cmd_video_acm_lut_satr4_table;
            pinfo->video_acm_lut_satr5_table = victoria_va_lgd_nt36772_5p5_1080p_cmd_video_acm_lut_satr5_table;
            pinfo->video_acm_lut_satr6_table = victoria_va_lgd_nt36772_5p5_1080p_cmd_video_acm_lut_satr6_table;
            pinfo->video_acm_lut_satr7_table = victoria_va_lgd_nt36772_5p5_1080p_cmd_video_acm_lut_satr7_table;
        }
        if (pinfo->gamma_support == 1)
        {
            pinfo->gamma_lut_table_R = victoria_va_lgd_nt36772_5p5_1080p_cmd_gamma_lut_table_R;
            pinfo->gamma_lut_table_G = victoria_va_lgd_nt36772_5p5_1080p_cmd_gamma_lut_table_G;
            pinfo->gamma_lut_table_B = victoria_va_lgd_nt36772_5p5_1080p_cmd_gamma_lut_table_B;
            pinfo->gamma_lut_table_len = ARRAY_SIZE(victoria_va_lgd_nt36772_5p5_1080p_cmd_gamma_lut_table_R);
            pinfo->igm_lut_table_R = victoria_va_lgd_nt36772_5p5_1080p_cmd_igm_lut_table_R;
            pinfo->igm_lut_table_G = victoria_va_lgd_nt36772_5p5_1080p_cmd_igm_lut_table_G;
            pinfo->igm_lut_table_B = victoria_va_lgd_nt36772_5p5_1080p_cmd_igm_lut_table_B;
            pinfo->igm_lut_table_len = ARRAY_SIZE(victoria_va_lgd_nt36772_5p5_1080p_cmd_igm_lut_table_R);
            pinfo->gmp_lut_table_low32bit = &victoria_va_lgd_nt36772_5p5_1080p_cmd_gmp_lut_table_low32bit[0][0][0];
            pinfo->gmp_lut_table_high4bit = &victoria_va_lgd_nt36772_5p5_1080p_cmd_gmp_lut_table_high4bit[0][0][0];
            pinfo->gmp_lut_table_len = ARRAY_SIZE(victoria_va_lgd_nt36772_5p5_1080p_cmd_gmp_lut_table_low32bit);
            pinfo->xcc_table = victoria_va_lgd_nt36772_5p5_1080p_cmd_xcc_table;
            pinfo->xcc_table_len = ARRAY_SIZE(victoria_va_lgd_nt36772_5p5_1080p_cmd_xcc_table);
        }
        break;
    case VICTORIA_VA_JDI_NT35696H_5P1_1080P_CMD_PANEL:
        if (pinfo->acm_support == 1)
        {
            pinfo->acm_lut_hue_table = victoria_va_jdi_nt35696h_5p1_1080p_cmd_acm_lut_hue_table;
            pinfo->acm_lut_hue_table_len = ARRAY_SIZE(victoria_va_jdi_nt35696h_5p1_1080p_cmd_acm_lut_hue_table);
            pinfo->acm_lut_sata_table = victoria_va_jdi_nt35696h_5p1_1080p_cmd_acm_lut_sata_table;
            pinfo->acm_lut_sata_table_len = ARRAY_SIZE(victoria_va_jdi_nt35696h_5p1_1080p_cmd_acm_lut_sata_table);
            pinfo->acm_lut_satr_table = victoria_va_jdi_nt35696h_5p1_1080p_cmd_acm_lut_satr_table;
            pinfo->acm_lut_satr_table_len = ARRAY_SIZE(victoria_va_jdi_nt35696h_5p1_1080p_cmd_acm_lut_satr_table);
            pinfo->acm_lut_satr0_table = victoria_va_jdi_nt35696h_5p1_1080p_cmd_acm_lut_satr0_table;
            pinfo->acm_lut_satr0_table_len = ARRAY_SIZE(victoria_va_jdi_nt35696h_5p1_1080p_cmd_acm_lut_satr0_table);
            pinfo->acm_lut_satr1_table = victoria_va_jdi_nt35696h_5p1_1080p_cmd_acm_lut_satr1_table;
            pinfo->acm_lut_satr1_table_len = ARRAY_SIZE(victoria_va_jdi_nt35696h_5p1_1080p_cmd_acm_lut_satr1_table);
            pinfo->acm_lut_satr2_table = victoria_va_jdi_nt35696h_5p1_1080p_cmd_acm_lut_satr2_table;
            pinfo->acm_lut_satr2_table_len = ARRAY_SIZE(victoria_va_jdi_nt35696h_5p1_1080p_cmd_acm_lut_satr2_table);
            pinfo->acm_lut_satr3_table = victoria_va_jdi_nt35696h_5p1_1080p_cmd_acm_lut_satr3_table;
            pinfo->acm_lut_satr3_table_len = ARRAY_SIZE(victoria_va_jdi_nt35696h_5p1_1080p_cmd_acm_lut_satr3_table);
            pinfo->acm_lut_satr4_table = victoria_va_jdi_nt35696h_5p1_1080p_cmd_acm_lut_satr4_table;
            pinfo->acm_lut_satr4_table_len = ARRAY_SIZE(victoria_va_jdi_nt35696h_5p1_1080p_cmd_acm_lut_satr4_table);
            pinfo->acm_lut_satr5_table = victoria_va_jdi_nt35696h_5p1_1080p_cmd_acm_lut_satr5_table;
            pinfo->acm_lut_satr5_table_len = ARRAY_SIZE(victoria_va_jdi_nt35696h_5p1_1080p_cmd_acm_lut_satr5_table);
            pinfo->acm_lut_satr6_table = victoria_va_jdi_nt35696h_5p1_1080p_cmd_acm_lut_satr6_table;
            pinfo->acm_lut_satr6_table_len = ARRAY_SIZE(victoria_va_jdi_nt35696h_5p1_1080p_cmd_acm_lut_satr6_table);
            pinfo->acm_lut_satr7_table = victoria_va_jdi_nt35696h_5p1_1080p_cmd_acm_lut_satr7_table;
            pinfo->acm_lut_satr7_table_len = ARRAY_SIZE(victoria_va_jdi_nt35696h_5p1_1080p_cmd_acm_lut_satr7_table);
            pinfo->video_acm_lut_hue_table = victoria_va_jdi_nt35696h_5p1_1080p_cmd_video_acm_lut_hue_table;
            pinfo->video_acm_lut_sata_table = victoria_va_jdi_nt35696h_5p1_1080p_cmd_video_acm_lut_sata_table;
            pinfo->video_acm_lut_satr0_table = victoria_va_jdi_nt35696h_5p1_1080p_cmd_video_acm_lut_satr0_table;
            pinfo->video_acm_lut_satr1_table = victoria_va_jdi_nt35696h_5p1_1080p_cmd_video_acm_lut_satr1_table;
            pinfo->video_acm_lut_satr2_table = victoria_va_jdi_nt35696h_5p1_1080p_cmd_video_acm_lut_satr2_table;
            pinfo->video_acm_lut_satr3_table = victoria_va_jdi_nt35696h_5p1_1080p_cmd_video_acm_lut_satr3_table;
            pinfo->video_acm_lut_satr4_table = victoria_va_jdi_nt35696h_5p1_1080p_cmd_video_acm_lut_satr4_table;
            pinfo->video_acm_lut_satr5_table = victoria_va_jdi_nt35696h_5p1_1080p_cmd_video_acm_lut_satr5_table;
            pinfo->video_acm_lut_satr6_table = victoria_va_jdi_nt35696h_5p1_1080p_cmd_video_acm_lut_satr6_table;
            pinfo->video_acm_lut_satr7_table = victoria_va_jdi_nt35696h_5p1_1080p_cmd_video_acm_lut_satr7_table;
        }
        if (pinfo->gamma_support == 1)
        {
            pinfo->gamma_lut_table_R = victoria_va_jdi_nt35696h_5p1_1080p_cmd_gamma_lut_table_R;
            pinfo->gamma_lut_table_G = victoria_va_jdi_nt35696h_5p1_1080p_cmd_gamma_lut_table_G;
            pinfo->gamma_lut_table_B = victoria_va_jdi_nt35696h_5p1_1080p_cmd_gamma_lut_table_B;
            pinfo->gamma_lut_table_len = ARRAY_SIZE(victoria_va_jdi_nt35696h_5p1_1080p_cmd_gamma_lut_table_R);
            pinfo->igm_lut_table_R = victoria_va_jdi_nt35696h_5p1_1080p_cmd_igm_lut_table_R;
            pinfo->igm_lut_table_G = victoria_va_jdi_nt35696h_5p1_1080p_cmd_igm_lut_table_G;
            pinfo->igm_lut_table_B = victoria_va_jdi_nt35696h_5p1_1080p_cmd_igm_lut_table_B;
            pinfo->igm_lut_table_len = ARRAY_SIZE(victoria_va_jdi_nt35696h_5p1_1080p_cmd_igm_lut_table_R);
            pinfo->gmp_lut_table_low32bit = &victoria_va_jdi_nt35696h_5p1_1080p_cmd_gmp_lut_table_low32bit[0][0][0];
            pinfo->gmp_lut_table_high4bit = &victoria_va_jdi_nt35696h_5p1_1080p_cmd_gmp_lut_table_high4bit[0][0][0];
            pinfo->gmp_lut_table_len = ARRAY_SIZE(victoria_va_jdi_nt35696h_5p1_1080p_cmd_gmp_lut_table_low32bit);
            pinfo->xcc_table = victoria_va_jdi_nt35696h_5p1_1080p_cmd_xcc_table;
            pinfo->xcc_table_len = ARRAY_SIZE(victoria_va_jdi_nt35696h_5p1_1080p_cmd_xcc_table);
        }
        break;
    case VICTORIA_VA_TIANMA_TD4322_5P5_1080P_CMD_PANEL:
        if (pinfo->acm_support == 1)
        {
            pinfo->acm_lut_hue_table = victoria_va_tianma_td4322_5p5_1080p_cmd_acm_lut_hue_table;
            pinfo->acm_lut_hue_table_len = ARRAY_SIZE(victoria_va_tianma_td4322_5p5_1080p_cmd_acm_lut_hue_table);
            pinfo->acm_lut_sata_table = victoria_va_tianma_td4322_5p5_1080p_cmd_acm_lut_sata_table;
            pinfo->acm_lut_sata_table_len = ARRAY_SIZE(victoria_va_tianma_td4322_5p5_1080p_cmd_acm_lut_sata_table);
            pinfo->acm_lut_satr_table = victoria_va_tianma_td4322_5p5_1080p_cmd_acm_lut_satr_table;
            pinfo->acm_lut_satr_table_len = ARRAY_SIZE(victoria_va_tianma_td4322_5p5_1080p_cmd_acm_lut_satr_table);
            pinfo->acm_lut_satr0_table = victoria_va_tianma_td4322_5p5_1080p_cmd_acm_lut_satr0_table;
            pinfo->acm_lut_satr0_table_len = ARRAY_SIZE(victoria_va_tianma_td4322_5p5_1080p_cmd_acm_lut_satr0_table);
            pinfo->acm_lut_satr1_table = victoria_va_tianma_td4322_5p5_1080p_cmd_acm_lut_satr1_table;
            pinfo->acm_lut_satr1_table_len = ARRAY_SIZE(victoria_va_tianma_td4322_5p5_1080p_cmd_acm_lut_satr1_table);
            pinfo->acm_lut_satr2_table = victoria_va_tianma_td4322_5p5_1080p_cmd_acm_lut_satr2_table;
            pinfo->acm_lut_satr2_table_len = ARRAY_SIZE(victoria_va_tianma_td4322_5p5_1080p_cmd_acm_lut_satr2_table);
            pinfo->acm_lut_satr3_table = victoria_va_tianma_td4322_5p5_1080p_cmd_acm_lut_satr3_table;
            pinfo->acm_lut_satr3_table_len = ARRAY_SIZE(victoria_va_tianma_td4322_5p5_1080p_cmd_acm_lut_satr3_table);
            pinfo->acm_lut_satr4_table = victoria_va_tianma_td4322_5p5_1080p_cmd_acm_lut_satr4_table;
            pinfo->acm_lut_satr4_table_len = ARRAY_SIZE(victoria_va_tianma_td4322_5p5_1080p_cmd_acm_lut_satr4_table);
            pinfo->acm_lut_satr5_table = victoria_va_tianma_td4322_5p5_1080p_cmd_acm_lut_satr5_table;
            pinfo->acm_lut_satr5_table_len = ARRAY_SIZE(victoria_va_tianma_td4322_5p5_1080p_cmd_acm_lut_satr5_table);
            pinfo->acm_lut_satr6_table = victoria_va_tianma_td4322_5p5_1080p_cmd_acm_lut_satr6_table;
            pinfo->acm_lut_satr6_table_len = ARRAY_SIZE(victoria_va_tianma_td4322_5p5_1080p_cmd_acm_lut_satr6_table);
            pinfo->acm_lut_satr7_table = victoria_va_tianma_td4322_5p5_1080p_cmd_acm_lut_satr7_table;
            pinfo->acm_lut_satr7_table_len = ARRAY_SIZE(victoria_va_tianma_td4322_5p5_1080p_cmd_acm_lut_satr7_table);
            pinfo->video_acm_lut_hue_table = victoria_va_tianma_td4322_5p5_1080p_cmd_video_acm_lut_hue_table;
            pinfo->video_acm_lut_sata_table = victoria_va_tianma_td4322_5p5_1080p_cmd_video_acm_lut_sata_table;
            pinfo->video_acm_lut_satr0_table = victoria_va_tianma_td4322_5p5_1080p_cmd_video_acm_lut_satr0_table;
            pinfo->video_acm_lut_satr1_table = victoria_va_tianma_td4322_5p5_1080p_cmd_video_acm_lut_satr1_table;
            pinfo->video_acm_lut_satr2_table = victoria_va_tianma_td4322_5p5_1080p_cmd_video_acm_lut_satr2_table;
            pinfo->video_acm_lut_satr3_table = victoria_va_tianma_td4322_5p5_1080p_cmd_video_acm_lut_satr3_table;
            pinfo->video_acm_lut_satr4_table = victoria_va_tianma_td4322_5p5_1080p_cmd_video_acm_lut_satr4_table;
            pinfo->video_acm_lut_satr5_table = victoria_va_tianma_td4322_5p5_1080p_cmd_video_acm_lut_satr5_table;
            pinfo->video_acm_lut_satr6_table = victoria_va_tianma_td4322_5p5_1080p_cmd_video_acm_lut_satr6_table;
            pinfo->video_acm_lut_satr7_table = victoria_va_tianma_td4322_5p5_1080p_cmd_video_acm_lut_satr7_table;
        }
        if (pinfo->gamma_support == 1)
        {
            pinfo->gamma_lut_table_R = victoria_va_tianma_td4322_5p5_1080p_cmd_gamma_lut_table_R;
            pinfo->gamma_lut_table_G = victoria_va_tianma_td4322_5p5_1080p_cmd_gamma_lut_table_G;
            pinfo->gamma_lut_table_B = victoria_va_tianma_td4322_5p5_1080p_cmd_gamma_lut_table_B;
            pinfo->gamma_lut_table_len = ARRAY_SIZE(victoria_va_tianma_td4322_5p5_1080p_cmd_gamma_lut_table_R);
            pinfo->igm_lut_table_R = victoria_va_tianma_td4322_5p5_1080p_cmd_igm_lut_table_R;
            pinfo->igm_lut_table_G = victoria_va_tianma_td4322_5p5_1080p_cmd_igm_lut_table_G;
            pinfo->igm_lut_table_B = victoria_va_tianma_td4322_5p5_1080p_cmd_igm_lut_table_B;
            pinfo->igm_lut_table_len = ARRAY_SIZE(victoria_va_tianma_td4322_5p5_1080p_cmd_igm_lut_table_R);
            pinfo->gmp_lut_table_low32bit = &victoria_va_tianma_td4322_5p5_1080p_cmd_gmp_lut_table_low32bit[0][0][0];
            pinfo->gmp_lut_table_high4bit = &victoria_va_tianma_td4322_5p5_1080p_cmd_gmp_lut_table_high4bit[0][0][0];
            pinfo->gmp_lut_table_len = ARRAY_SIZE(victoria_va_tianma_td4322_5p5_1080p_cmd_gmp_lut_table_low32bit);
            pinfo->xcc_table = victoria_va_tianma_td4322_5p5_1080p_cmd_xcc_table;
            pinfo->xcc_table_len = ARRAY_SIZE(victoria_va_tianma_td4322_5p5_1080p_cmd_xcc_table);
        }
        break;
    case DEFAULT_AUO_OTM1901A_5P2_1080P_VIDEO_DEFAULT_PANEL:
        if (pinfo->acm_support == 1)
        {
            pinfo->acm_lut_hue_table = default_auo_otm1901a_5p2_1080p_video_default_acm_lut_hue_table;
            pinfo->acm_lut_hue_table_len = ARRAY_SIZE(default_auo_otm1901a_5p2_1080p_video_default_acm_lut_hue_table);
            pinfo->acm_lut_sata_table = default_auo_otm1901a_5p2_1080p_video_default_acm_lut_sata_table;
            pinfo->acm_lut_sata_table_len = ARRAY_SIZE(default_auo_otm1901a_5p2_1080p_video_default_acm_lut_sata_table);
            pinfo->acm_lut_satr_table = default_auo_otm1901a_5p2_1080p_video_default_acm_lut_satr_table;
            pinfo->acm_lut_satr_table_len = ARRAY_SIZE(default_auo_otm1901a_5p2_1080p_video_default_acm_lut_satr_table);
            pinfo->acm_lut_satr0_table = default_auo_otm1901a_5p2_1080p_video_default_acm_lut_satr0_table;
            pinfo->acm_lut_satr0_table_len = ARRAY_SIZE(default_auo_otm1901a_5p2_1080p_video_default_acm_lut_satr0_table);
            pinfo->acm_lut_satr1_table = default_auo_otm1901a_5p2_1080p_video_default_acm_lut_satr1_table;
            pinfo->acm_lut_satr1_table_len = ARRAY_SIZE(default_auo_otm1901a_5p2_1080p_video_default_acm_lut_satr1_table);
            pinfo->acm_lut_satr2_table = default_auo_otm1901a_5p2_1080p_video_default_acm_lut_satr2_table;
            pinfo->acm_lut_satr2_table_len = ARRAY_SIZE(default_auo_otm1901a_5p2_1080p_video_default_acm_lut_satr2_table);
            pinfo->acm_lut_satr3_table = default_auo_otm1901a_5p2_1080p_video_default_acm_lut_satr3_table;
            pinfo->acm_lut_satr3_table_len = ARRAY_SIZE(default_auo_otm1901a_5p2_1080p_video_default_acm_lut_satr3_table);
            pinfo->acm_lut_satr4_table = default_auo_otm1901a_5p2_1080p_video_default_acm_lut_satr4_table;
            pinfo->acm_lut_satr4_table_len = ARRAY_SIZE(default_auo_otm1901a_5p2_1080p_video_default_acm_lut_satr4_table);
            pinfo->acm_lut_satr5_table = default_auo_otm1901a_5p2_1080p_video_default_acm_lut_satr5_table;
            pinfo->acm_lut_satr5_table_len = ARRAY_SIZE(default_auo_otm1901a_5p2_1080p_video_default_acm_lut_satr5_table);
            pinfo->acm_lut_satr6_table = default_auo_otm1901a_5p2_1080p_video_default_acm_lut_satr6_table;
            pinfo->acm_lut_satr6_table_len = ARRAY_SIZE(default_auo_otm1901a_5p2_1080p_video_default_acm_lut_satr6_table);
            pinfo->acm_lut_satr7_table = default_auo_otm1901a_5p2_1080p_video_default_acm_lut_satr7_table;
            pinfo->acm_lut_satr7_table_len = ARRAY_SIZE(default_auo_otm1901a_5p2_1080p_video_default_acm_lut_satr7_table);
            pinfo->video_acm_lut_hue_table = default_auo_otm1901a_5p2_1080p_video_default_video_acm_lut_hue_table;
            pinfo->video_acm_lut_sata_table = default_auo_otm1901a_5p2_1080p_video_default_video_acm_lut_sata_table;
            pinfo->video_acm_lut_satr0_table = default_auo_otm1901a_5p2_1080p_video_default_video_acm_lut_satr0_table;
            pinfo->video_acm_lut_satr1_table = default_auo_otm1901a_5p2_1080p_video_default_video_acm_lut_satr1_table;
            pinfo->video_acm_lut_satr2_table = default_auo_otm1901a_5p2_1080p_video_default_video_acm_lut_satr2_table;
            pinfo->video_acm_lut_satr3_table = default_auo_otm1901a_5p2_1080p_video_default_video_acm_lut_satr3_table;
            pinfo->video_acm_lut_satr4_table = default_auo_otm1901a_5p2_1080p_video_default_video_acm_lut_satr4_table;
            pinfo->video_acm_lut_satr5_table = default_auo_otm1901a_5p2_1080p_video_default_video_acm_lut_satr5_table;
            pinfo->video_acm_lut_satr6_table = default_auo_otm1901a_5p2_1080p_video_default_video_acm_lut_satr6_table;
            pinfo->video_acm_lut_satr7_table = default_auo_otm1901a_5p2_1080p_video_default_video_acm_lut_satr7_table;
        }
        if (pinfo->gamma_support == 1)
        {
            pinfo->gamma_lut_table_R = default_auo_otm1901a_5p2_1080p_video_default_gamma_lut_table_R;
            pinfo->gamma_lut_table_G = default_auo_otm1901a_5p2_1080p_video_default_gamma_lut_table_G;
            pinfo->gamma_lut_table_B = default_auo_otm1901a_5p2_1080p_video_default_gamma_lut_table_B;
            pinfo->gamma_lut_table_len = ARRAY_SIZE(default_auo_otm1901a_5p2_1080p_video_default_gamma_lut_table_R);
            pinfo->igm_lut_table_R = default_auo_otm1901a_5p2_1080p_video_default_igm_lut_table_R;
            pinfo->igm_lut_table_G = default_auo_otm1901a_5p2_1080p_video_default_igm_lut_table_G;
            pinfo->igm_lut_table_B = default_auo_otm1901a_5p2_1080p_video_default_igm_lut_table_B;
            pinfo->igm_lut_table_len = ARRAY_SIZE(default_auo_otm1901a_5p2_1080p_video_default_igm_lut_table_R);
            pinfo->gmp_lut_table_low32bit = &default_auo_otm1901a_5p2_1080p_video_default_gmp_lut_table_low32bit[0][0][0];
            pinfo->gmp_lut_table_high4bit = &default_auo_otm1901a_5p2_1080p_video_default_gmp_lut_table_high4bit[0][0][0];
            pinfo->gmp_lut_table_len = ARRAY_SIZE(default_auo_otm1901a_5p2_1080p_video_default_gmp_lut_table_low32bit);
            pinfo->xcc_table = default_auo_otm1901a_5p2_1080p_video_default_xcc_table;
            pinfo->xcc_table_len = ARRAY_SIZE(default_auo_otm1901a_5p2_1080p_video_default_xcc_table);
        }
        break;
    case VICKY_VA_JDI_S6D1HA2_5P5_2K_CMD_PANEL:
        if (pinfo->acm_support == 1)
        {
            pinfo->acm_lut_hue_table = vicky_va_jdi_s6d1ha2_5p5_2k_cmd_acm_lut_hue_table;
            pinfo->acm_lut_hue_table_len = ARRAY_SIZE(vicky_va_jdi_s6d1ha2_5p5_2k_cmd_acm_lut_hue_table);
            pinfo->acm_lut_sata_table = vicky_va_jdi_s6d1ha2_5p5_2k_cmd_acm_lut_sata_table;
            pinfo->acm_lut_sata_table_len = ARRAY_SIZE(vicky_va_jdi_s6d1ha2_5p5_2k_cmd_acm_lut_sata_table);
            pinfo->acm_lut_satr_table = vicky_va_jdi_s6d1ha2_5p5_2k_cmd_acm_lut_satr_table;
            pinfo->acm_lut_satr_table_len = ARRAY_SIZE(vicky_va_jdi_s6d1ha2_5p5_2k_cmd_acm_lut_satr_table);
            pinfo->acm_lut_satr0_table = vicky_va_jdi_s6d1ha2_5p5_2k_cmd_acm_lut_satr0_table;
            pinfo->acm_lut_satr0_table_len = ARRAY_SIZE(vicky_va_jdi_s6d1ha2_5p5_2k_cmd_acm_lut_satr0_table);
            pinfo->acm_lut_satr1_table = vicky_va_jdi_s6d1ha2_5p5_2k_cmd_acm_lut_satr1_table;
            pinfo->acm_lut_satr1_table_len = ARRAY_SIZE(vicky_va_jdi_s6d1ha2_5p5_2k_cmd_acm_lut_satr1_table);
            pinfo->acm_lut_satr2_table = vicky_va_jdi_s6d1ha2_5p5_2k_cmd_acm_lut_satr2_table;
            pinfo->acm_lut_satr2_table_len = ARRAY_SIZE(vicky_va_jdi_s6d1ha2_5p5_2k_cmd_acm_lut_satr2_table);
            pinfo->acm_lut_satr3_table = vicky_va_jdi_s6d1ha2_5p5_2k_cmd_acm_lut_satr3_table;
            pinfo->acm_lut_satr3_table_len = ARRAY_SIZE(vicky_va_jdi_s6d1ha2_5p5_2k_cmd_acm_lut_satr3_table);
            pinfo->acm_lut_satr4_table = vicky_va_jdi_s6d1ha2_5p5_2k_cmd_acm_lut_satr4_table;
            pinfo->acm_lut_satr4_table_len = ARRAY_SIZE(vicky_va_jdi_s6d1ha2_5p5_2k_cmd_acm_lut_satr4_table);
            pinfo->acm_lut_satr5_table = vicky_va_jdi_s6d1ha2_5p5_2k_cmd_acm_lut_satr5_table;
            pinfo->acm_lut_satr5_table_len = ARRAY_SIZE(vicky_va_jdi_s6d1ha2_5p5_2k_cmd_acm_lut_satr5_table);
            pinfo->acm_lut_satr6_table = vicky_va_jdi_s6d1ha2_5p5_2k_cmd_acm_lut_satr6_table;
            pinfo->acm_lut_satr6_table_len = ARRAY_SIZE(vicky_va_jdi_s6d1ha2_5p5_2k_cmd_acm_lut_satr6_table);
            pinfo->acm_lut_satr7_table = vicky_va_jdi_s6d1ha2_5p5_2k_cmd_acm_lut_satr7_table;
            pinfo->acm_lut_satr7_table_len = ARRAY_SIZE(vicky_va_jdi_s6d1ha2_5p5_2k_cmd_acm_lut_satr7_table);
            pinfo->video_acm_lut_hue_table = vicky_va_jdi_s6d1ha2_5p5_2k_cmd_video_acm_lut_hue_table;
            pinfo->video_acm_lut_sata_table = vicky_va_jdi_s6d1ha2_5p5_2k_cmd_video_acm_lut_sata_table;
            pinfo->video_acm_lut_satr0_table = vicky_va_jdi_s6d1ha2_5p5_2k_cmd_video_acm_lut_satr0_table;
            pinfo->video_acm_lut_satr1_table = vicky_va_jdi_s6d1ha2_5p5_2k_cmd_video_acm_lut_satr1_table;
            pinfo->video_acm_lut_satr2_table = vicky_va_jdi_s6d1ha2_5p5_2k_cmd_video_acm_lut_satr2_table;
            pinfo->video_acm_lut_satr3_table = vicky_va_jdi_s6d1ha2_5p5_2k_cmd_video_acm_lut_satr3_table;
            pinfo->video_acm_lut_satr4_table = vicky_va_jdi_s6d1ha2_5p5_2k_cmd_video_acm_lut_satr4_table;
            pinfo->video_acm_lut_satr5_table = vicky_va_jdi_s6d1ha2_5p5_2k_cmd_video_acm_lut_satr5_table;
            pinfo->video_acm_lut_satr6_table = vicky_va_jdi_s6d1ha2_5p5_2k_cmd_video_acm_lut_satr6_table;
            pinfo->video_acm_lut_satr7_table = vicky_va_jdi_s6d1ha2_5p5_2k_cmd_video_acm_lut_satr7_table;
        }
        if (pinfo->gamma_support == 1)
        {
            pinfo->gamma_lut_table_R = vicky_va_jdi_s6d1ha2_5p5_2k_cmd_gamma_lut_table_R;
            pinfo->gamma_lut_table_G = vicky_va_jdi_s6d1ha2_5p5_2k_cmd_gamma_lut_table_G;
            pinfo->gamma_lut_table_B = vicky_va_jdi_s6d1ha2_5p5_2k_cmd_gamma_lut_table_B;
            pinfo->gamma_lut_table_len = ARRAY_SIZE(vicky_va_jdi_s6d1ha2_5p5_2k_cmd_gamma_lut_table_R);
            pinfo->igm_lut_table_R = vicky_va_jdi_s6d1ha2_5p5_2k_cmd_igm_lut_table_R;
            pinfo->igm_lut_table_G = vicky_va_jdi_s6d1ha2_5p5_2k_cmd_igm_lut_table_G;
            pinfo->igm_lut_table_B = vicky_va_jdi_s6d1ha2_5p5_2k_cmd_igm_lut_table_B;
            pinfo->igm_lut_table_len = ARRAY_SIZE(vicky_va_jdi_s6d1ha2_5p5_2k_cmd_igm_lut_table_R);
            pinfo->gmp_lut_table_low32bit = &vicky_va_jdi_s6d1ha2_5p5_2k_cmd_gmp_lut_table_low32bit[0][0][0];
            pinfo->gmp_lut_table_high4bit = &vicky_va_jdi_s6d1ha2_5p5_2k_cmd_gmp_lut_table_high4bit[0][0][0];
            pinfo->gmp_lut_table_len = ARRAY_SIZE(vicky_va_jdi_s6d1ha2_5p5_2k_cmd_gmp_lut_table_low32bit);
            pinfo->xcc_table = vicky_va_jdi_s6d1ha2_5p5_2k_cmd_xcc_table;
            pinfo->xcc_table_len = ARRAY_SIZE(vicky_va_jdi_s6d1ha2_5p5_2k_cmd_xcc_table);
        }
        break;
    case VICKY_VA_JDI_OTM2503B_5P5_2K_CMD_PANEL:
        if (pinfo->acm_support == 1)
        {
            pinfo->acm_lut_hue_table = vicky_va_jdi_otm2503b_5p5_2k_cmd_acm_lut_hue_table;
            pinfo->acm_lut_hue_table_len = ARRAY_SIZE(vicky_va_jdi_otm2503b_5p5_2k_cmd_acm_lut_hue_table);
            pinfo->acm_lut_sata_table = vicky_va_jdi_otm2503b_5p5_2k_cmd_acm_lut_sata_table;
            pinfo->acm_lut_sata_table_len = ARRAY_SIZE(vicky_va_jdi_otm2503b_5p5_2k_cmd_acm_lut_sata_table);
            pinfo->acm_lut_satr_table = vicky_va_jdi_otm2503b_5p5_2k_cmd_acm_lut_satr_table;
            pinfo->acm_lut_satr_table_len = ARRAY_SIZE(vicky_va_jdi_otm2503b_5p5_2k_cmd_acm_lut_satr_table);
            pinfo->acm_lut_satr0_table = vicky_va_jdi_otm2503b_5p5_2k_cmd_acm_lut_satr0_table;
            pinfo->acm_lut_satr0_table_len = ARRAY_SIZE(vicky_va_jdi_otm2503b_5p5_2k_cmd_acm_lut_satr0_table);
            pinfo->acm_lut_satr1_table = vicky_va_jdi_otm2503b_5p5_2k_cmd_acm_lut_satr1_table;
            pinfo->acm_lut_satr1_table_len = ARRAY_SIZE(vicky_va_jdi_otm2503b_5p5_2k_cmd_acm_lut_satr1_table);
            pinfo->acm_lut_satr2_table = vicky_va_jdi_otm2503b_5p5_2k_cmd_acm_lut_satr2_table;
            pinfo->acm_lut_satr2_table_len = ARRAY_SIZE(vicky_va_jdi_otm2503b_5p5_2k_cmd_acm_lut_satr2_table);
            pinfo->acm_lut_satr3_table = vicky_va_jdi_otm2503b_5p5_2k_cmd_acm_lut_satr3_table;
            pinfo->acm_lut_satr3_table_len = ARRAY_SIZE(vicky_va_jdi_otm2503b_5p5_2k_cmd_acm_lut_satr3_table);
            pinfo->acm_lut_satr4_table = vicky_va_jdi_otm2503b_5p5_2k_cmd_acm_lut_satr4_table;
            pinfo->acm_lut_satr4_table_len = ARRAY_SIZE(vicky_va_jdi_otm2503b_5p5_2k_cmd_acm_lut_satr4_table);
            pinfo->acm_lut_satr5_table = vicky_va_jdi_otm2503b_5p5_2k_cmd_acm_lut_satr5_table;
            pinfo->acm_lut_satr5_table_len = ARRAY_SIZE(vicky_va_jdi_otm2503b_5p5_2k_cmd_acm_lut_satr5_table);
            pinfo->acm_lut_satr6_table = vicky_va_jdi_otm2503b_5p5_2k_cmd_acm_lut_satr6_table;
            pinfo->acm_lut_satr6_table_len = ARRAY_SIZE(vicky_va_jdi_otm2503b_5p5_2k_cmd_acm_lut_satr6_table);
            pinfo->acm_lut_satr7_table = vicky_va_jdi_otm2503b_5p5_2k_cmd_acm_lut_satr7_table;
            pinfo->acm_lut_satr7_table_len = ARRAY_SIZE(vicky_va_jdi_otm2503b_5p5_2k_cmd_acm_lut_satr7_table);
            pinfo->video_acm_lut_hue_table = vicky_va_jdi_otm2503b_5p5_2k_cmd_video_acm_lut_hue_table;
            pinfo->video_acm_lut_sata_table = vicky_va_jdi_otm2503b_5p5_2k_cmd_video_acm_lut_sata_table;
            pinfo->video_acm_lut_satr0_table = vicky_va_jdi_otm2503b_5p5_2k_cmd_video_acm_lut_satr0_table;
            pinfo->video_acm_lut_satr1_table = vicky_va_jdi_otm2503b_5p5_2k_cmd_video_acm_lut_satr1_table;
            pinfo->video_acm_lut_satr2_table = vicky_va_jdi_otm2503b_5p5_2k_cmd_video_acm_lut_satr2_table;
            pinfo->video_acm_lut_satr3_table = vicky_va_jdi_otm2503b_5p5_2k_cmd_video_acm_lut_satr3_table;
            pinfo->video_acm_lut_satr4_table = vicky_va_jdi_otm2503b_5p5_2k_cmd_video_acm_lut_satr4_table;
            pinfo->video_acm_lut_satr5_table = vicky_va_jdi_otm2503b_5p5_2k_cmd_video_acm_lut_satr5_table;
            pinfo->video_acm_lut_satr6_table = vicky_va_jdi_otm2503b_5p5_2k_cmd_video_acm_lut_satr6_table;
            pinfo->video_acm_lut_satr7_table = vicky_va_jdi_otm2503b_5p5_2k_cmd_video_acm_lut_satr7_table;
        }
        if (pinfo->gamma_support == 1)
        {
            pinfo->gamma_lut_table_R = vicky_va_jdi_otm2503b_5p5_2k_cmd_gamma_lut_table_R;
            pinfo->gamma_lut_table_G = vicky_va_jdi_otm2503b_5p5_2k_cmd_gamma_lut_table_G;
            pinfo->gamma_lut_table_B = vicky_va_jdi_otm2503b_5p5_2k_cmd_gamma_lut_table_B;
            pinfo->gamma_lut_table_len = ARRAY_SIZE(vicky_va_jdi_otm2503b_5p5_2k_cmd_gamma_lut_table_R);
            pinfo->igm_lut_table_R = vicky_va_jdi_otm2503b_5p5_2k_cmd_igm_lut_table_R;
            pinfo->igm_lut_table_G = vicky_va_jdi_otm2503b_5p5_2k_cmd_igm_lut_table_G;
            pinfo->igm_lut_table_B = vicky_va_jdi_otm2503b_5p5_2k_cmd_igm_lut_table_B;
            pinfo->igm_lut_table_len = ARRAY_SIZE(vicky_va_jdi_otm2503b_5p5_2k_cmd_igm_lut_table_R);
            pinfo->gmp_lut_table_low32bit = &vicky_va_jdi_otm2503b_5p5_2k_cmd_gmp_lut_table_low32bit[0][0][0];
            pinfo->gmp_lut_table_high4bit = &vicky_va_jdi_otm2503b_5p5_2k_cmd_gmp_lut_table_high4bit[0][0][0];
            pinfo->gmp_lut_table_len = ARRAY_SIZE(vicky_va_jdi_otm2503b_5p5_2k_cmd_gmp_lut_table_low32bit);
            pinfo->xcc_table = vicky_va_jdi_otm2503b_5p5_2k_cmd_xcc_table;
            pinfo->xcc_table_len = ARRAY_SIZE(vicky_va_jdi_otm2503b_5p5_2k_cmd_xcc_table);
        }
        break;
    case STF_JDI_R63452_5P2_1080P_CMD_PANEL:
        if (pinfo->acm_support == 1)
        {
            pinfo->acm_lut_hue_table = stf_jdi_r63452_5p2_1080p_cmd_acm_lut_hue_table;
            pinfo->acm_lut_hue_table_len = ARRAY_SIZE(stf_jdi_r63452_5p2_1080p_cmd_acm_lut_hue_table);
            pinfo->acm_lut_sata_table = stf_jdi_r63452_5p2_1080p_cmd_acm_lut_sata_table;
            pinfo->acm_lut_sata_table_len = ARRAY_SIZE(stf_jdi_r63452_5p2_1080p_cmd_acm_lut_sata_table);
            pinfo->acm_lut_satr_table = stf_jdi_r63452_5p2_1080p_cmd_acm_lut_satr_table;
            pinfo->acm_lut_satr_table_len = ARRAY_SIZE(stf_jdi_r63452_5p2_1080p_cmd_acm_lut_satr_table);
            pinfo->acm_lut_satr0_table = stf_jdi_r63452_5p2_1080p_cmd_acm_lut_satr0_table;
            pinfo->acm_lut_satr0_table_len = ARRAY_SIZE(stf_jdi_r63452_5p2_1080p_cmd_acm_lut_satr0_table);
            pinfo->acm_lut_satr1_table = stf_jdi_r63452_5p2_1080p_cmd_acm_lut_satr1_table;
            pinfo->acm_lut_satr1_table_len = ARRAY_SIZE(stf_jdi_r63452_5p2_1080p_cmd_acm_lut_satr1_table);
            pinfo->acm_lut_satr2_table = stf_jdi_r63452_5p2_1080p_cmd_acm_lut_satr2_table;
            pinfo->acm_lut_satr2_table_len = ARRAY_SIZE(stf_jdi_r63452_5p2_1080p_cmd_acm_lut_satr2_table);
            pinfo->acm_lut_satr3_table = stf_jdi_r63452_5p2_1080p_cmd_acm_lut_satr3_table;
            pinfo->acm_lut_satr3_table_len = ARRAY_SIZE(stf_jdi_r63452_5p2_1080p_cmd_acm_lut_satr3_table);
            pinfo->acm_lut_satr4_table = stf_jdi_r63452_5p2_1080p_cmd_acm_lut_satr4_table;
            pinfo->acm_lut_satr4_table_len = ARRAY_SIZE(stf_jdi_r63452_5p2_1080p_cmd_acm_lut_satr4_table);
            pinfo->acm_lut_satr5_table = stf_jdi_r63452_5p2_1080p_cmd_acm_lut_satr5_table;
            pinfo->acm_lut_satr5_table_len = ARRAY_SIZE(stf_jdi_r63452_5p2_1080p_cmd_acm_lut_satr5_table);
            pinfo->acm_lut_satr6_table = stf_jdi_r63452_5p2_1080p_cmd_acm_lut_satr6_table;
            pinfo->acm_lut_satr6_table_len = ARRAY_SIZE(stf_jdi_r63452_5p2_1080p_cmd_acm_lut_satr6_table);
            pinfo->acm_lut_satr7_table = stf_jdi_r63452_5p2_1080p_cmd_acm_lut_satr7_table;
            pinfo->acm_lut_satr7_table_len = ARRAY_SIZE(stf_jdi_r63452_5p2_1080p_cmd_acm_lut_satr7_table);
            pinfo->video_acm_lut_hue_table = stf_jdi_r63452_5p2_1080p_cmd_video_acm_lut_hue_table;
            pinfo->video_acm_lut_sata_table = stf_jdi_r63452_5p2_1080p_cmd_video_acm_lut_sata_table;
            pinfo->video_acm_lut_satr0_table = stf_jdi_r63452_5p2_1080p_cmd_video_acm_lut_satr0_table;
            pinfo->video_acm_lut_satr1_table = stf_jdi_r63452_5p2_1080p_cmd_video_acm_lut_satr1_table;
            pinfo->video_acm_lut_satr2_table = stf_jdi_r63452_5p2_1080p_cmd_video_acm_lut_satr2_table;
            pinfo->video_acm_lut_satr3_table = stf_jdi_r63452_5p2_1080p_cmd_video_acm_lut_satr3_table;
            pinfo->video_acm_lut_satr4_table = stf_jdi_r63452_5p2_1080p_cmd_video_acm_lut_satr4_table;
            pinfo->video_acm_lut_satr5_table = stf_jdi_r63452_5p2_1080p_cmd_video_acm_lut_satr5_table;
            pinfo->video_acm_lut_satr6_table = stf_jdi_r63452_5p2_1080p_cmd_video_acm_lut_satr6_table;
            pinfo->video_acm_lut_satr7_table = stf_jdi_r63452_5p2_1080p_cmd_video_acm_lut_satr7_table;
        }
        if (pinfo->gamma_support == 1)
        {
            pinfo->gamma_lut_table_R = stf_jdi_r63452_5p2_1080p_cmd_gamma_lut_table_R;
            pinfo->gamma_lut_table_G = stf_jdi_r63452_5p2_1080p_cmd_gamma_lut_table_G;
            pinfo->gamma_lut_table_B = stf_jdi_r63452_5p2_1080p_cmd_gamma_lut_table_B;
            pinfo->gamma_lut_table_len = ARRAY_SIZE(stf_jdi_r63452_5p2_1080p_cmd_gamma_lut_table_R);
            pinfo->igm_lut_table_R = stf_jdi_r63452_5p2_1080p_cmd_igm_lut_table_R;
            pinfo->igm_lut_table_G = stf_jdi_r63452_5p2_1080p_cmd_igm_lut_table_G;
            pinfo->igm_lut_table_B = stf_jdi_r63452_5p2_1080p_cmd_igm_lut_table_B;
            pinfo->igm_lut_table_len = ARRAY_SIZE(stf_jdi_r63452_5p2_1080p_cmd_igm_lut_table_R);
            pinfo->gmp_lut_table_low32bit = &stf_jdi_r63452_5p2_1080p_cmd_gmp_lut_table_low32bit[0][0][0];
            pinfo->gmp_lut_table_high4bit = &stf_jdi_r63452_5p2_1080p_cmd_gmp_lut_table_high4bit[0][0][0];
            pinfo->gmp_lut_table_len = ARRAY_SIZE(stf_jdi_r63452_5p2_1080p_cmd_gmp_lut_table_low32bit);
            pinfo->xcc_table = stf_jdi_r63452_5p2_1080p_cmd_xcc_table;
            pinfo->xcc_table_len = ARRAY_SIZE(stf_jdi_r63452_5p2_1080p_cmd_xcc_table);
        }
        break;
    case STF_LG_R69006_5P2_1080P_CMD_PANEL:
        if (pinfo->acm_support == 1)
        {
            pinfo->acm_lut_hue_table = stf_lg_r69006_5p2_1080p_cmd_acm_lut_hue_table;
            pinfo->acm_lut_hue_table_len = ARRAY_SIZE(stf_lg_r69006_5p2_1080p_cmd_acm_lut_hue_table);
            pinfo->acm_lut_sata_table = stf_lg_r69006_5p2_1080p_cmd_acm_lut_sata_table;
            pinfo->acm_lut_sata_table_len = ARRAY_SIZE(stf_lg_r69006_5p2_1080p_cmd_acm_lut_sata_table);
            pinfo->acm_lut_satr_table = stf_lg_r69006_5p2_1080p_cmd_acm_lut_satr_table;
            pinfo->acm_lut_satr_table_len = ARRAY_SIZE(stf_lg_r69006_5p2_1080p_cmd_acm_lut_satr_table);
            pinfo->acm_lut_satr0_table = stf_lg_r69006_5p2_1080p_cmd_acm_lut_satr0_table;
            pinfo->acm_lut_satr0_table_len = ARRAY_SIZE(stf_lg_r69006_5p2_1080p_cmd_acm_lut_satr0_table);
            pinfo->acm_lut_satr1_table = stf_lg_r69006_5p2_1080p_cmd_acm_lut_satr1_table;
            pinfo->acm_lut_satr1_table_len = ARRAY_SIZE(stf_lg_r69006_5p2_1080p_cmd_acm_lut_satr1_table);
            pinfo->acm_lut_satr2_table = stf_lg_r69006_5p2_1080p_cmd_acm_lut_satr2_table;
            pinfo->acm_lut_satr2_table_len = ARRAY_SIZE(stf_lg_r69006_5p2_1080p_cmd_acm_lut_satr2_table);
            pinfo->acm_lut_satr3_table = stf_lg_r69006_5p2_1080p_cmd_acm_lut_satr3_table;
            pinfo->acm_lut_satr3_table_len = ARRAY_SIZE(stf_lg_r69006_5p2_1080p_cmd_acm_lut_satr3_table);
            pinfo->acm_lut_satr4_table = stf_lg_r69006_5p2_1080p_cmd_acm_lut_satr4_table;
            pinfo->acm_lut_satr4_table_len = ARRAY_SIZE(stf_lg_r69006_5p2_1080p_cmd_acm_lut_satr4_table);
            pinfo->acm_lut_satr5_table = stf_lg_r69006_5p2_1080p_cmd_acm_lut_satr5_table;
            pinfo->acm_lut_satr5_table_len = ARRAY_SIZE(stf_lg_r69006_5p2_1080p_cmd_acm_lut_satr5_table);
            pinfo->acm_lut_satr6_table = stf_lg_r69006_5p2_1080p_cmd_acm_lut_satr6_table;
            pinfo->acm_lut_satr6_table_len = ARRAY_SIZE(stf_lg_r69006_5p2_1080p_cmd_acm_lut_satr6_table);
            pinfo->acm_lut_satr7_table = stf_lg_r69006_5p2_1080p_cmd_acm_lut_satr7_table;
            pinfo->acm_lut_satr7_table_len = ARRAY_SIZE(stf_lg_r69006_5p2_1080p_cmd_acm_lut_satr7_table);
            pinfo->video_acm_lut_hue_table = stf_lg_r69006_5p2_1080p_cmd_video_acm_lut_hue_table;
            pinfo->video_acm_lut_sata_table = stf_lg_r69006_5p2_1080p_cmd_video_acm_lut_sata_table;
            pinfo->video_acm_lut_satr0_table = stf_lg_r69006_5p2_1080p_cmd_video_acm_lut_satr0_table;
            pinfo->video_acm_lut_satr1_table = stf_lg_r69006_5p2_1080p_cmd_video_acm_lut_satr1_table;
            pinfo->video_acm_lut_satr2_table = stf_lg_r69006_5p2_1080p_cmd_video_acm_lut_satr2_table;
            pinfo->video_acm_lut_satr3_table = stf_lg_r69006_5p2_1080p_cmd_video_acm_lut_satr3_table;
            pinfo->video_acm_lut_satr4_table = stf_lg_r69006_5p2_1080p_cmd_video_acm_lut_satr4_table;
            pinfo->video_acm_lut_satr5_table = stf_lg_r69006_5p2_1080p_cmd_video_acm_lut_satr5_table;
            pinfo->video_acm_lut_satr6_table = stf_lg_r69006_5p2_1080p_cmd_video_acm_lut_satr6_table;
            pinfo->video_acm_lut_satr7_table = stf_lg_r69006_5p2_1080p_cmd_video_acm_lut_satr7_table;
        }
        if (pinfo->gamma_support == 1)
        {
            pinfo->gamma_lut_table_R = stf_lg_r69006_5p2_1080p_cmd_gamma_lut_table_R;
            pinfo->gamma_lut_table_G = stf_lg_r69006_5p2_1080p_cmd_gamma_lut_table_G;
            pinfo->gamma_lut_table_B = stf_lg_r69006_5p2_1080p_cmd_gamma_lut_table_B;
            pinfo->gamma_lut_table_len = ARRAY_SIZE(stf_lg_r69006_5p2_1080p_cmd_gamma_lut_table_R);
            pinfo->igm_lut_table_R = stf_lg_r69006_5p2_1080p_cmd_igm_lut_table_R;
            pinfo->igm_lut_table_G = stf_lg_r69006_5p2_1080p_cmd_igm_lut_table_G;
            pinfo->igm_lut_table_B = stf_lg_r69006_5p2_1080p_cmd_igm_lut_table_B;
            pinfo->igm_lut_table_len = ARRAY_SIZE(stf_lg_r69006_5p2_1080p_cmd_igm_lut_table_R);
            pinfo->gmp_lut_table_low32bit = &stf_lg_r69006_5p2_1080p_cmd_gmp_lut_table_low32bit[0][0][0];
            pinfo->gmp_lut_table_high4bit = &stf_lg_r69006_5p2_1080p_cmd_gmp_lut_table_high4bit[0][0][0];
            pinfo->gmp_lut_table_len = ARRAY_SIZE(stf_lg_r69006_5p2_1080p_cmd_gmp_lut_table_low32bit);
            pinfo->xcc_table = stf_lg_r69006_5p2_1080p_cmd_xcc_table;
            pinfo->xcc_table_len = ARRAY_SIZE(stf_lg_r69006_5p2_1080p_cmd_xcc_table);
        }
        break;
    case STF_SHARP_NT35695_5P2_1080P_CMD_PANEL:
        if (pinfo->acm_support == 1)
        {
            pinfo->acm_lut_hue_table = stf_sharp_nt35695_5p2_1080p_cmd_acm_lut_hue_table;
            pinfo->acm_lut_hue_table_len = ARRAY_SIZE(stf_sharp_nt35695_5p2_1080p_cmd_acm_lut_hue_table);
            pinfo->acm_lut_sata_table = stf_sharp_nt35695_5p2_1080p_cmd_acm_lut_sata_table;
            pinfo->acm_lut_sata_table_len = ARRAY_SIZE(stf_sharp_nt35695_5p2_1080p_cmd_acm_lut_sata_table);
            pinfo->acm_lut_satr_table = stf_sharp_nt35695_5p2_1080p_cmd_acm_lut_satr_table;
            pinfo->acm_lut_satr_table_len = ARRAY_SIZE(stf_sharp_nt35695_5p2_1080p_cmd_acm_lut_satr_table);
            pinfo->acm_lut_satr0_table = stf_sharp_nt35695_5p2_1080p_cmd_acm_lut_satr0_table;
            pinfo->acm_lut_satr0_table_len = ARRAY_SIZE(stf_sharp_nt35695_5p2_1080p_cmd_acm_lut_satr0_table);
            pinfo->acm_lut_satr1_table = stf_sharp_nt35695_5p2_1080p_cmd_acm_lut_satr1_table;
            pinfo->acm_lut_satr1_table_len = ARRAY_SIZE(stf_sharp_nt35695_5p2_1080p_cmd_acm_lut_satr1_table);
            pinfo->acm_lut_satr2_table = stf_sharp_nt35695_5p2_1080p_cmd_acm_lut_satr2_table;
            pinfo->acm_lut_satr2_table_len = ARRAY_SIZE(stf_sharp_nt35695_5p2_1080p_cmd_acm_lut_satr2_table);
            pinfo->acm_lut_satr3_table = stf_sharp_nt35695_5p2_1080p_cmd_acm_lut_satr3_table;
            pinfo->acm_lut_satr3_table_len = ARRAY_SIZE(stf_sharp_nt35695_5p2_1080p_cmd_acm_lut_satr3_table);
            pinfo->acm_lut_satr4_table = stf_sharp_nt35695_5p2_1080p_cmd_acm_lut_satr4_table;
            pinfo->acm_lut_satr4_table_len = ARRAY_SIZE(stf_sharp_nt35695_5p2_1080p_cmd_acm_lut_satr4_table);
            pinfo->acm_lut_satr5_table = stf_sharp_nt35695_5p2_1080p_cmd_acm_lut_satr5_table;
            pinfo->acm_lut_satr5_table_len = ARRAY_SIZE(stf_sharp_nt35695_5p2_1080p_cmd_acm_lut_satr5_table);
            pinfo->acm_lut_satr6_table = stf_sharp_nt35695_5p2_1080p_cmd_acm_lut_satr6_table;
            pinfo->acm_lut_satr6_table_len = ARRAY_SIZE(stf_sharp_nt35695_5p2_1080p_cmd_acm_lut_satr6_table);
            pinfo->acm_lut_satr7_table = stf_sharp_nt35695_5p2_1080p_cmd_acm_lut_satr7_table;
            pinfo->acm_lut_satr7_table_len = ARRAY_SIZE(stf_sharp_nt35695_5p2_1080p_cmd_acm_lut_satr7_table);
            pinfo->video_acm_lut_hue_table = stf_sharp_nt35695_5p2_1080p_cmd_video_acm_lut_hue_table;
            pinfo->video_acm_lut_sata_table = stf_sharp_nt35695_5p2_1080p_cmd_video_acm_lut_sata_table;
            pinfo->video_acm_lut_satr0_table = stf_sharp_nt35695_5p2_1080p_cmd_video_acm_lut_satr0_table;
            pinfo->video_acm_lut_satr1_table = stf_sharp_nt35695_5p2_1080p_cmd_video_acm_lut_satr1_table;
            pinfo->video_acm_lut_satr2_table = stf_sharp_nt35695_5p2_1080p_cmd_video_acm_lut_satr2_table;
            pinfo->video_acm_lut_satr3_table = stf_sharp_nt35695_5p2_1080p_cmd_video_acm_lut_satr3_table;
            pinfo->video_acm_lut_satr4_table = stf_sharp_nt35695_5p2_1080p_cmd_video_acm_lut_satr4_table;
            pinfo->video_acm_lut_satr5_table = stf_sharp_nt35695_5p2_1080p_cmd_video_acm_lut_satr5_table;
            pinfo->video_acm_lut_satr6_table = stf_sharp_nt35695_5p2_1080p_cmd_video_acm_lut_satr6_table;
            pinfo->video_acm_lut_satr7_table = stf_sharp_nt35695_5p2_1080p_cmd_video_acm_lut_satr7_table;
        }
        if (pinfo->gamma_support == 1)
        {
            pinfo->gamma_lut_table_R = stf_sharp_nt35695_5p2_1080p_cmd_gamma_lut_table_R;
            pinfo->gamma_lut_table_G = stf_sharp_nt35695_5p2_1080p_cmd_gamma_lut_table_G;
            pinfo->gamma_lut_table_B = stf_sharp_nt35695_5p2_1080p_cmd_gamma_lut_table_B;
            pinfo->gamma_lut_table_len = ARRAY_SIZE(stf_sharp_nt35695_5p2_1080p_cmd_gamma_lut_table_R);
            pinfo->igm_lut_table_R = stf_sharp_nt35695_5p2_1080p_cmd_igm_lut_table_R;
            pinfo->igm_lut_table_G = stf_sharp_nt35695_5p2_1080p_cmd_igm_lut_table_G;
            pinfo->igm_lut_table_B = stf_sharp_nt35695_5p2_1080p_cmd_igm_lut_table_B;
            pinfo->igm_lut_table_len = ARRAY_SIZE(stf_sharp_nt35695_5p2_1080p_cmd_igm_lut_table_R);
            pinfo->gmp_lut_table_low32bit = &stf_sharp_nt35695_5p2_1080p_cmd_gmp_lut_table_low32bit[0][0][0];
            pinfo->gmp_lut_table_high4bit = &stf_sharp_nt35695_5p2_1080p_cmd_gmp_lut_table_high4bit[0][0][0];
            pinfo->gmp_lut_table_len = ARRAY_SIZE(stf_sharp_nt35695_5p2_1080p_cmd_gmp_lut_table_low32bit);
            pinfo->xcc_table = stf_sharp_nt35695_5p2_1080p_cmd_xcc_table;
            pinfo->xcc_table_len = ARRAY_SIZE(stf_sharp_nt35695_5p2_1080p_cmd_xcc_table);
        }
        break;
    case BAC_TIANMA_TD4310_5P5_1080P_VIDEO_PANEL:
        if (pinfo->acm_support == 1)
        {
            pinfo->acm_lut_hue_table = bac_tianma_td4310_5p5_1080p_video_acm_lut_hue_table;
            pinfo->acm_lut_hue_table_len = ARRAY_SIZE(bac_tianma_td4310_5p5_1080p_video_acm_lut_hue_table);
            pinfo->acm_lut_sata_table = bac_tianma_td4310_5p5_1080p_video_acm_lut_sata_table;
            pinfo->acm_lut_sata_table_len = ARRAY_SIZE(bac_tianma_td4310_5p5_1080p_video_acm_lut_sata_table);
            pinfo->acm_lut_satr_table = bac_tianma_td4310_5p5_1080p_video_acm_lut_satr_table;
            pinfo->acm_lut_satr_table_len = ARRAY_SIZE(bac_tianma_td4310_5p5_1080p_video_acm_lut_satr_table);
            pinfo->acm_lut_satr0_table = bac_tianma_td4310_5p5_1080p_video_acm_lut_satr0_table;
            pinfo->acm_lut_satr0_table_len = ARRAY_SIZE(bac_tianma_td4310_5p5_1080p_video_acm_lut_satr0_table);
            pinfo->acm_lut_satr1_table = bac_tianma_td4310_5p5_1080p_video_acm_lut_satr1_table;
            pinfo->acm_lut_satr1_table_len = ARRAY_SIZE(bac_tianma_td4310_5p5_1080p_video_acm_lut_satr1_table);
            pinfo->acm_lut_satr2_table = bac_tianma_td4310_5p5_1080p_video_acm_lut_satr2_table;
            pinfo->acm_lut_satr2_table_len = ARRAY_SIZE(bac_tianma_td4310_5p5_1080p_video_acm_lut_satr2_table);
            pinfo->acm_lut_satr3_table = bac_tianma_td4310_5p5_1080p_video_acm_lut_satr3_table;
            pinfo->acm_lut_satr3_table_len = ARRAY_SIZE(bac_tianma_td4310_5p5_1080p_video_acm_lut_satr3_table);
            pinfo->acm_lut_satr4_table = bac_tianma_td4310_5p5_1080p_video_acm_lut_satr4_table;
            pinfo->acm_lut_satr4_table_len = ARRAY_SIZE(bac_tianma_td4310_5p5_1080p_video_acm_lut_satr4_table);
            pinfo->acm_lut_satr5_table = bac_tianma_td4310_5p5_1080p_video_acm_lut_satr5_table;
            pinfo->acm_lut_satr5_table_len = ARRAY_SIZE(bac_tianma_td4310_5p5_1080p_video_acm_lut_satr5_table);
            pinfo->acm_lut_satr6_table = bac_tianma_td4310_5p5_1080p_video_acm_lut_satr6_table;
            pinfo->acm_lut_satr6_table_len = ARRAY_SIZE(bac_tianma_td4310_5p5_1080p_video_acm_lut_satr6_table);
            pinfo->acm_lut_satr7_table = bac_tianma_td4310_5p5_1080p_video_acm_lut_satr7_table;
            pinfo->acm_lut_satr7_table_len = ARRAY_SIZE(bac_tianma_td4310_5p5_1080p_video_acm_lut_satr7_table);
            pinfo->video_acm_lut_hue_table = bac_tianma_td4310_5p5_1080p_video_video_acm_lut_hue_table;
            pinfo->video_acm_lut_sata_table = bac_tianma_td4310_5p5_1080p_video_video_acm_lut_sata_table;
            pinfo->video_acm_lut_satr0_table = bac_tianma_td4310_5p5_1080p_video_video_acm_lut_satr0_table;
            pinfo->video_acm_lut_satr1_table = bac_tianma_td4310_5p5_1080p_video_video_acm_lut_satr1_table;
            pinfo->video_acm_lut_satr2_table = bac_tianma_td4310_5p5_1080p_video_video_acm_lut_satr2_table;
            pinfo->video_acm_lut_satr3_table = bac_tianma_td4310_5p5_1080p_video_video_acm_lut_satr3_table;
            pinfo->video_acm_lut_satr4_table = bac_tianma_td4310_5p5_1080p_video_video_acm_lut_satr4_table;
            pinfo->video_acm_lut_satr5_table = bac_tianma_td4310_5p5_1080p_video_video_acm_lut_satr5_table;
            pinfo->video_acm_lut_satr6_table = bac_tianma_td4310_5p5_1080p_video_video_acm_lut_satr6_table;
            pinfo->video_acm_lut_satr7_table = bac_tianma_td4310_5p5_1080p_video_video_acm_lut_satr7_table;
        }
        if (pinfo->gamma_support == 1)
        {
            pinfo->gamma_lut_table_R = bac_tianma_td4310_5p5_1080p_video_gamma_lut_table_R;
            pinfo->gamma_lut_table_G = bac_tianma_td4310_5p5_1080p_video_gamma_lut_table_G;
            pinfo->gamma_lut_table_B = bac_tianma_td4310_5p5_1080p_video_gamma_lut_table_B;
            pinfo->gamma_lut_table_len = ARRAY_SIZE(bac_tianma_td4310_5p5_1080p_video_gamma_lut_table_R);
            pinfo->igm_lut_table_R = bac_tianma_td4310_5p5_1080p_video_igm_lut_table_R;
            pinfo->igm_lut_table_G = bac_tianma_td4310_5p5_1080p_video_igm_lut_table_G;
            pinfo->igm_lut_table_B = bac_tianma_td4310_5p5_1080p_video_igm_lut_table_B;
            pinfo->igm_lut_table_len = ARRAY_SIZE(bac_tianma_td4310_5p5_1080p_video_igm_lut_table_R);
            pinfo->gmp_lut_table_low32bit = &bac_tianma_td4310_5p5_1080p_video_gmp_lut_table_low32bit[0][0][0];
            pinfo->gmp_lut_table_high4bit = &bac_tianma_td4310_5p5_1080p_video_gmp_lut_table_high4bit[0][0][0];
            pinfo->gmp_lut_table_len = ARRAY_SIZE(bac_tianma_td4310_5p5_1080p_video_gmp_lut_table_low32bit);
            pinfo->xcc_table = bac_tianma_td4310_5p5_1080p_video_xcc_table;
            pinfo->xcc_table_len = ARRAY_SIZE(bac_tianma_td4310_5p5_1080p_video_xcc_table);
        }
        break;
    case STF_TIANMA_TD4310_5P2_1080P_VIDEO_PANEL:
        if (pinfo->acm_support == 1)
        {
            pinfo->acm_lut_hue_table = stf_tianma_td4310_5p2_1080p_video_acm_lut_hue_table;
            pinfo->acm_lut_hue_table_len = ARRAY_SIZE(stf_tianma_td4310_5p2_1080p_video_acm_lut_hue_table);
            pinfo->acm_lut_sata_table = stf_tianma_td4310_5p2_1080p_video_acm_lut_sata_table;
            pinfo->acm_lut_sata_table_len = ARRAY_SIZE(stf_tianma_td4310_5p2_1080p_video_acm_lut_sata_table);
            pinfo->acm_lut_satr_table = stf_tianma_td4310_5p2_1080p_video_acm_lut_satr_table;
            pinfo->acm_lut_satr_table_len = ARRAY_SIZE(stf_tianma_td4310_5p2_1080p_video_acm_lut_satr_table);
            pinfo->acm_lut_satr0_table = stf_tianma_td4310_5p2_1080p_video_acm_lut_satr0_table;
            pinfo->acm_lut_satr0_table_len = ARRAY_SIZE(stf_tianma_td4310_5p2_1080p_video_acm_lut_satr0_table);
            pinfo->acm_lut_satr1_table = stf_tianma_td4310_5p2_1080p_video_acm_lut_satr1_table;
            pinfo->acm_lut_satr1_table_len = ARRAY_SIZE(stf_tianma_td4310_5p2_1080p_video_acm_lut_satr1_table);
            pinfo->acm_lut_satr2_table = stf_tianma_td4310_5p2_1080p_video_acm_lut_satr2_table;
            pinfo->acm_lut_satr2_table_len = ARRAY_SIZE(stf_tianma_td4310_5p2_1080p_video_acm_lut_satr2_table);
            pinfo->acm_lut_satr3_table = stf_tianma_td4310_5p2_1080p_video_acm_lut_satr3_table;
            pinfo->acm_lut_satr3_table_len = ARRAY_SIZE(stf_tianma_td4310_5p2_1080p_video_acm_lut_satr3_table);
            pinfo->acm_lut_satr4_table = stf_tianma_td4310_5p2_1080p_video_acm_lut_satr4_table;
            pinfo->acm_lut_satr4_table_len = ARRAY_SIZE(stf_tianma_td4310_5p2_1080p_video_acm_lut_satr4_table);
            pinfo->acm_lut_satr5_table = stf_tianma_td4310_5p2_1080p_video_acm_lut_satr5_table;
            pinfo->acm_lut_satr5_table_len = ARRAY_SIZE(stf_tianma_td4310_5p2_1080p_video_acm_lut_satr5_table);
            pinfo->acm_lut_satr6_table = stf_tianma_td4310_5p2_1080p_video_acm_lut_satr6_table;
            pinfo->acm_lut_satr6_table_len = ARRAY_SIZE(stf_tianma_td4310_5p2_1080p_video_acm_lut_satr6_table);
            pinfo->acm_lut_satr7_table = stf_tianma_td4310_5p2_1080p_video_acm_lut_satr7_table;
            pinfo->acm_lut_satr7_table_len = ARRAY_SIZE(stf_tianma_td4310_5p2_1080p_video_acm_lut_satr7_table);
            pinfo->video_acm_lut_hue_table = stf_tianma_td4310_5p2_1080p_video_video_acm_lut_hue_table;
            pinfo->video_acm_lut_sata_table = stf_tianma_td4310_5p2_1080p_video_video_acm_lut_sata_table;
            pinfo->video_acm_lut_satr0_table = stf_tianma_td4310_5p2_1080p_video_video_acm_lut_satr0_table;
            pinfo->video_acm_lut_satr1_table = stf_tianma_td4310_5p2_1080p_video_video_acm_lut_satr1_table;
            pinfo->video_acm_lut_satr2_table = stf_tianma_td4310_5p2_1080p_video_video_acm_lut_satr2_table;
            pinfo->video_acm_lut_satr3_table = stf_tianma_td4310_5p2_1080p_video_video_acm_lut_satr3_table;
            pinfo->video_acm_lut_satr4_table = stf_tianma_td4310_5p2_1080p_video_video_acm_lut_satr4_table;
            pinfo->video_acm_lut_satr5_table = stf_tianma_td4310_5p2_1080p_video_video_acm_lut_satr5_table;
            pinfo->video_acm_lut_satr6_table = stf_tianma_td4310_5p2_1080p_video_video_acm_lut_satr6_table;
            pinfo->video_acm_lut_satr7_table = stf_tianma_td4310_5p2_1080p_video_video_acm_lut_satr7_table;
        }
        if (pinfo->gamma_support == 1)
        {
            pinfo->gamma_lut_table_R = stf_tianma_td4310_5p2_1080p_video_gamma_lut_table_R;
            pinfo->gamma_lut_table_G = stf_tianma_td4310_5p2_1080p_video_gamma_lut_table_G;
            pinfo->gamma_lut_table_B = stf_tianma_td4310_5p2_1080p_video_gamma_lut_table_B;
            pinfo->gamma_lut_table_len = ARRAY_SIZE(stf_tianma_td4310_5p2_1080p_video_gamma_lut_table_R);
            pinfo->igm_lut_table_R = stf_tianma_td4310_5p2_1080p_video_igm_lut_table_R;
            pinfo->igm_lut_table_G = stf_tianma_td4310_5p2_1080p_video_igm_lut_table_G;
            pinfo->igm_lut_table_B = stf_tianma_td4310_5p2_1080p_video_igm_lut_table_B;
            pinfo->igm_lut_table_len = ARRAY_SIZE(stf_tianma_td4310_5p2_1080p_video_igm_lut_table_R);
            pinfo->gmp_lut_table_low32bit = &stf_tianma_td4310_5p2_1080p_video_gmp_lut_table_low32bit[0][0][0];
            pinfo->gmp_lut_table_high4bit = &stf_tianma_td4310_5p2_1080p_video_gmp_lut_table_high4bit[0][0][0];
            pinfo->gmp_lut_table_len = ARRAY_SIZE(stf_tianma_td4310_5p2_1080p_video_gmp_lut_table_low32bit);
            pinfo->xcc_table = stf_tianma_td4310_5p2_1080p_video_xcc_table;
            pinfo->xcc_table_len = ARRAY_SIZE(stf_tianma_td4310_5p2_1080p_video_xcc_table);
        }
        break;
    case BAC_AUO_NT36672_5P5_1080P_VIDEO_PANEL:
        if (pinfo->acm_support == 1)
        {
            pinfo->acm_lut_hue_table = bac_auo_nt36672_5p5_1080p_video_acm_lut_hue_table;
            pinfo->acm_lut_hue_table_len = ARRAY_SIZE(bac_auo_nt36672_5p5_1080p_video_acm_lut_hue_table);
            pinfo->acm_lut_sata_table = bac_auo_nt36672_5p5_1080p_video_acm_lut_sata_table;
            pinfo->acm_lut_sata_table_len = ARRAY_SIZE(bac_auo_nt36672_5p5_1080p_video_acm_lut_sata_table);
            pinfo->acm_lut_satr_table = bac_auo_nt36672_5p5_1080p_video_acm_lut_satr_table;
            pinfo->acm_lut_satr_table_len = ARRAY_SIZE(bac_auo_nt36672_5p5_1080p_video_acm_lut_satr_table);
            pinfo->acm_lut_satr0_table = bac_auo_nt36672_5p5_1080p_video_acm_lut_satr0_table;
            pinfo->acm_lut_satr0_table_len = ARRAY_SIZE(bac_auo_nt36672_5p5_1080p_video_acm_lut_satr0_table);
            pinfo->acm_lut_satr1_table = bac_auo_nt36672_5p5_1080p_video_acm_lut_satr1_table;
            pinfo->acm_lut_satr1_table_len = ARRAY_SIZE(bac_auo_nt36672_5p5_1080p_video_acm_lut_satr1_table);
            pinfo->acm_lut_satr2_table = bac_auo_nt36672_5p5_1080p_video_acm_lut_satr2_table;
            pinfo->acm_lut_satr2_table_len = ARRAY_SIZE(bac_auo_nt36672_5p5_1080p_video_acm_lut_satr2_table);
            pinfo->acm_lut_satr3_table = bac_auo_nt36672_5p5_1080p_video_acm_lut_satr3_table;
            pinfo->acm_lut_satr3_table_len = ARRAY_SIZE(bac_auo_nt36672_5p5_1080p_video_acm_lut_satr3_table);
            pinfo->acm_lut_satr4_table = bac_auo_nt36672_5p5_1080p_video_acm_lut_satr4_table;
            pinfo->acm_lut_satr4_table_len = ARRAY_SIZE(bac_auo_nt36672_5p5_1080p_video_acm_lut_satr4_table);
            pinfo->acm_lut_satr5_table = bac_auo_nt36672_5p5_1080p_video_acm_lut_satr5_table;
            pinfo->acm_lut_satr5_table_len = ARRAY_SIZE(bac_auo_nt36672_5p5_1080p_video_acm_lut_satr5_table);
            pinfo->acm_lut_satr6_table = bac_auo_nt36672_5p5_1080p_video_acm_lut_satr6_table;
            pinfo->acm_lut_satr6_table_len = ARRAY_SIZE(bac_auo_nt36672_5p5_1080p_video_acm_lut_satr6_table);
            pinfo->acm_lut_satr7_table = bac_auo_nt36672_5p5_1080p_video_acm_lut_satr7_table;
            pinfo->acm_lut_satr7_table_len = ARRAY_SIZE(bac_auo_nt36672_5p5_1080p_video_acm_lut_satr7_table);
            pinfo->video_acm_lut_hue_table = bac_auo_nt36672_5p5_1080p_video_video_acm_lut_hue_table;
            pinfo->video_acm_lut_sata_table = bac_auo_nt36672_5p5_1080p_video_video_acm_lut_sata_table;
            pinfo->video_acm_lut_satr0_table = bac_auo_nt36672_5p5_1080p_video_video_acm_lut_satr0_table;
            pinfo->video_acm_lut_satr1_table = bac_auo_nt36672_5p5_1080p_video_video_acm_lut_satr1_table;
            pinfo->video_acm_lut_satr2_table = bac_auo_nt36672_5p5_1080p_video_video_acm_lut_satr2_table;
            pinfo->video_acm_lut_satr3_table = bac_auo_nt36672_5p5_1080p_video_video_acm_lut_satr3_table;
            pinfo->video_acm_lut_satr4_table = bac_auo_nt36672_5p5_1080p_video_video_acm_lut_satr4_table;
            pinfo->video_acm_lut_satr5_table = bac_auo_nt36672_5p5_1080p_video_video_acm_lut_satr5_table;
            pinfo->video_acm_lut_satr6_table = bac_auo_nt36672_5p5_1080p_video_video_acm_lut_satr6_table;
            pinfo->video_acm_lut_satr7_table = bac_auo_nt36672_5p5_1080p_video_video_acm_lut_satr7_table;
        }
        if (pinfo->gamma_support == 1)
        {
            pinfo->gamma_lut_table_R = bac_auo_nt36672_5p5_1080p_video_gamma_lut_table_R;
            pinfo->gamma_lut_table_G = bac_auo_nt36672_5p5_1080p_video_gamma_lut_table_G;
            pinfo->gamma_lut_table_B = bac_auo_nt36672_5p5_1080p_video_gamma_lut_table_B;
            pinfo->gamma_lut_table_len = ARRAY_SIZE(bac_auo_nt36672_5p5_1080p_video_gamma_lut_table_R);
            pinfo->igm_lut_table_R = bac_auo_nt36672_5p5_1080p_video_igm_lut_table_R;
            pinfo->igm_lut_table_G = bac_auo_nt36672_5p5_1080p_video_igm_lut_table_G;
            pinfo->igm_lut_table_B = bac_auo_nt36672_5p5_1080p_video_igm_lut_table_B;
            pinfo->igm_lut_table_len = ARRAY_SIZE(bac_auo_nt36672_5p5_1080p_video_igm_lut_table_R);
            pinfo->gmp_lut_table_low32bit = &bac_auo_nt36672_5p5_1080p_video_gmp_lut_table_low32bit[0][0][0];
            pinfo->gmp_lut_table_high4bit = &bac_auo_nt36672_5p5_1080p_video_gmp_lut_table_high4bit[0][0][0];
            pinfo->gmp_lut_table_len = ARRAY_SIZE(bac_auo_nt36672_5p5_1080p_video_gmp_lut_table_low32bit);
            pinfo->xcc_table = bac_auo_nt36672_5p5_1080p_video_xcc_table;
            pinfo->xcc_table_len = ARRAY_SIZE(bac_auo_nt36672_5p5_1080p_video_xcc_table);
        }
        break;
    case STF_V3_LG_R69006_5P2_1080P_CMD_PANEL:
        if (pinfo->acm_support == 1)
        {
            pinfo->acm_lut_hue_table = stf_v3_lg_r69006_5p2_1080p_cmd_acm_lut_hue_table;
            pinfo->acm_lut_hue_table_len = ARRAY_SIZE(stf_v3_lg_r69006_5p2_1080p_cmd_acm_lut_hue_table);
            pinfo->acm_lut_sata_table = stf_v3_lg_r69006_5p2_1080p_cmd_acm_lut_sata_table;
            pinfo->acm_lut_sata_table_len = ARRAY_SIZE(stf_v3_lg_r69006_5p2_1080p_cmd_acm_lut_sata_table);
            pinfo->acm_lut_satr_table = stf_v3_lg_r69006_5p2_1080p_cmd_acm_lut_satr_table;
            pinfo->acm_lut_satr_table_len = ARRAY_SIZE(stf_v3_lg_r69006_5p2_1080p_cmd_acm_lut_satr_table);
            pinfo->acm_lut_satr0_table = stf_v3_lg_r69006_5p2_1080p_cmd_acm_lut_satr0_table;
            pinfo->acm_lut_satr0_table_len = ARRAY_SIZE(stf_v3_lg_r69006_5p2_1080p_cmd_acm_lut_satr0_table);
            pinfo->acm_lut_satr1_table = stf_v3_lg_r69006_5p2_1080p_cmd_acm_lut_satr1_table;
            pinfo->acm_lut_satr1_table_len = ARRAY_SIZE(stf_v3_lg_r69006_5p2_1080p_cmd_acm_lut_satr1_table);
            pinfo->acm_lut_satr2_table = stf_v3_lg_r69006_5p2_1080p_cmd_acm_lut_satr2_table;
            pinfo->acm_lut_satr2_table_len = ARRAY_SIZE(stf_v3_lg_r69006_5p2_1080p_cmd_acm_lut_satr2_table);
            pinfo->acm_lut_satr3_table = stf_v3_lg_r69006_5p2_1080p_cmd_acm_lut_satr3_table;
            pinfo->acm_lut_satr3_table_len = ARRAY_SIZE(stf_v3_lg_r69006_5p2_1080p_cmd_acm_lut_satr3_table);
            pinfo->acm_lut_satr4_table = stf_v3_lg_r69006_5p2_1080p_cmd_acm_lut_satr4_table;
            pinfo->acm_lut_satr4_table_len = ARRAY_SIZE(stf_v3_lg_r69006_5p2_1080p_cmd_acm_lut_satr4_table);
            pinfo->acm_lut_satr5_table = stf_v3_lg_r69006_5p2_1080p_cmd_acm_lut_satr5_table;
            pinfo->acm_lut_satr5_table_len = ARRAY_SIZE(stf_v3_lg_r69006_5p2_1080p_cmd_acm_lut_satr5_table);
            pinfo->acm_lut_satr6_table = stf_v3_lg_r69006_5p2_1080p_cmd_acm_lut_satr6_table;
            pinfo->acm_lut_satr6_table_len = ARRAY_SIZE(stf_v3_lg_r69006_5p2_1080p_cmd_acm_lut_satr6_table);
            pinfo->acm_lut_satr7_table = stf_v3_lg_r69006_5p2_1080p_cmd_acm_lut_satr7_table;
            pinfo->acm_lut_satr7_table_len = ARRAY_SIZE(stf_v3_lg_r69006_5p2_1080p_cmd_acm_lut_satr7_table);
            pinfo->video_acm_lut_hue_table = stf_v3_lg_r69006_5p2_1080p_cmd_video_acm_lut_hue_table;
            pinfo->video_acm_lut_sata_table = stf_v3_lg_r69006_5p2_1080p_cmd_video_acm_lut_sata_table;
            pinfo->video_acm_lut_satr0_table = stf_v3_lg_r69006_5p2_1080p_cmd_video_acm_lut_satr0_table;
            pinfo->video_acm_lut_satr1_table = stf_v3_lg_r69006_5p2_1080p_cmd_video_acm_lut_satr1_table;
            pinfo->video_acm_lut_satr2_table = stf_v3_lg_r69006_5p2_1080p_cmd_video_acm_lut_satr2_table;
            pinfo->video_acm_lut_satr3_table = stf_v3_lg_r69006_5p2_1080p_cmd_video_acm_lut_satr3_table;
            pinfo->video_acm_lut_satr4_table = stf_v3_lg_r69006_5p2_1080p_cmd_video_acm_lut_satr4_table;
            pinfo->video_acm_lut_satr5_table = stf_v3_lg_r69006_5p2_1080p_cmd_video_acm_lut_satr5_table;
            pinfo->video_acm_lut_satr6_table = stf_v3_lg_r69006_5p2_1080p_cmd_video_acm_lut_satr6_table;
            pinfo->video_acm_lut_satr7_table = stf_v3_lg_r69006_5p2_1080p_cmd_video_acm_lut_satr7_table;
        }
        if (pinfo->gamma_support == 1)
        {
            pinfo->gamma_lut_table_R = stf_v3_lg_r69006_5p2_1080p_cmd_gamma_lut_table_R;
            pinfo->gamma_lut_table_G = stf_v3_lg_r69006_5p2_1080p_cmd_gamma_lut_table_G;
            pinfo->gamma_lut_table_B = stf_v3_lg_r69006_5p2_1080p_cmd_gamma_lut_table_B;
            pinfo->gamma_lut_table_len = ARRAY_SIZE(stf_v3_lg_r69006_5p2_1080p_cmd_gamma_lut_table_R);
            pinfo->igm_lut_table_R = stf_v3_lg_r69006_5p2_1080p_cmd_igm_lut_table_R;
            pinfo->igm_lut_table_G = stf_v3_lg_r69006_5p2_1080p_cmd_igm_lut_table_G;
            pinfo->igm_lut_table_B = stf_v3_lg_r69006_5p2_1080p_cmd_igm_lut_table_B;
            pinfo->igm_lut_table_len = ARRAY_SIZE(stf_v3_lg_r69006_5p2_1080p_cmd_igm_lut_table_R);
            pinfo->gmp_lut_table_low32bit = &stf_v3_lg_r69006_5p2_1080p_cmd_gmp_lut_table_low32bit[0][0][0];
            pinfo->gmp_lut_table_high4bit = &stf_v3_lg_r69006_5p2_1080p_cmd_gmp_lut_table_high4bit[0][0][0];
            pinfo->gmp_lut_table_len = ARRAY_SIZE(stf_v3_lg_r69006_5p2_1080p_cmd_gmp_lut_table_low32bit);
            pinfo->xcc_table = stf_v3_lg_r69006_5p2_1080p_cmd_xcc_table;
            pinfo->xcc_table_len = ARRAY_SIZE(stf_v3_lg_r69006_5p2_1080p_cmd_xcc_table);
        }
        break;
    case STF_V3_JDI_R63452_5P2_1080P_CMD_PANEL:
        if (pinfo->acm_support == 1)
        {
            pinfo->acm_lut_hue_table = stf_v3_jdi_r63452_5p2_1080p_cmd_acm_lut_hue_table;
            pinfo->acm_lut_hue_table_len = ARRAY_SIZE(stf_v3_jdi_r63452_5p2_1080p_cmd_acm_lut_hue_table);
            pinfo->acm_lut_sata_table = stf_v3_jdi_r63452_5p2_1080p_cmd_acm_lut_sata_table;
            pinfo->acm_lut_sata_table_len = ARRAY_SIZE(stf_v3_jdi_r63452_5p2_1080p_cmd_acm_lut_sata_table);
            pinfo->acm_lut_satr_table = stf_v3_jdi_r63452_5p2_1080p_cmd_acm_lut_satr_table;
            pinfo->acm_lut_satr_table_len = ARRAY_SIZE(stf_v3_jdi_r63452_5p2_1080p_cmd_acm_lut_satr_table);
            pinfo->acm_lut_satr0_table = stf_v3_jdi_r63452_5p2_1080p_cmd_acm_lut_satr0_table;
            pinfo->acm_lut_satr0_table_len = ARRAY_SIZE(stf_v3_jdi_r63452_5p2_1080p_cmd_acm_lut_satr0_table);
            pinfo->acm_lut_satr1_table = stf_v3_jdi_r63452_5p2_1080p_cmd_acm_lut_satr1_table;
            pinfo->acm_lut_satr1_table_len = ARRAY_SIZE(stf_v3_jdi_r63452_5p2_1080p_cmd_acm_lut_satr1_table);
            pinfo->acm_lut_satr2_table = stf_v3_jdi_r63452_5p2_1080p_cmd_acm_lut_satr2_table;
            pinfo->acm_lut_satr2_table_len = ARRAY_SIZE(stf_v3_jdi_r63452_5p2_1080p_cmd_acm_lut_satr2_table);
            pinfo->acm_lut_satr3_table = stf_v3_jdi_r63452_5p2_1080p_cmd_acm_lut_satr3_table;
            pinfo->acm_lut_satr3_table_len = ARRAY_SIZE(stf_v3_jdi_r63452_5p2_1080p_cmd_acm_lut_satr3_table);
            pinfo->acm_lut_satr4_table = stf_v3_jdi_r63452_5p2_1080p_cmd_acm_lut_satr4_table;
            pinfo->acm_lut_satr4_table_len = ARRAY_SIZE(stf_v3_jdi_r63452_5p2_1080p_cmd_acm_lut_satr4_table);
            pinfo->acm_lut_satr5_table = stf_v3_jdi_r63452_5p2_1080p_cmd_acm_lut_satr5_table;
            pinfo->acm_lut_satr5_table_len = ARRAY_SIZE(stf_v3_jdi_r63452_5p2_1080p_cmd_acm_lut_satr5_table);
            pinfo->acm_lut_satr6_table = stf_v3_jdi_r63452_5p2_1080p_cmd_acm_lut_satr6_table;
            pinfo->acm_lut_satr6_table_len = ARRAY_SIZE(stf_v3_jdi_r63452_5p2_1080p_cmd_acm_lut_satr6_table);
            pinfo->acm_lut_satr7_table = stf_v3_jdi_r63452_5p2_1080p_cmd_acm_lut_satr7_table;
            pinfo->acm_lut_satr7_table_len = ARRAY_SIZE(stf_v3_jdi_r63452_5p2_1080p_cmd_acm_lut_satr7_table);
            pinfo->video_acm_lut_hue_table = stf_v3_jdi_r63452_5p2_1080p_cmd_video_acm_lut_hue_table;
            pinfo->video_acm_lut_sata_table = stf_v3_jdi_r63452_5p2_1080p_cmd_video_acm_lut_sata_table;
            pinfo->video_acm_lut_satr0_table = stf_v3_jdi_r63452_5p2_1080p_cmd_video_acm_lut_satr0_table;
            pinfo->video_acm_lut_satr1_table = stf_v3_jdi_r63452_5p2_1080p_cmd_video_acm_lut_satr1_table;
            pinfo->video_acm_lut_satr2_table = stf_v3_jdi_r63452_5p2_1080p_cmd_video_acm_lut_satr2_table;
            pinfo->video_acm_lut_satr3_table = stf_v3_jdi_r63452_5p2_1080p_cmd_video_acm_lut_satr3_table;
            pinfo->video_acm_lut_satr4_table = stf_v3_jdi_r63452_5p2_1080p_cmd_video_acm_lut_satr4_table;
            pinfo->video_acm_lut_satr5_table = stf_v3_jdi_r63452_5p2_1080p_cmd_video_acm_lut_satr5_table;
            pinfo->video_acm_lut_satr6_table = stf_v3_jdi_r63452_5p2_1080p_cmd_video_acm_lut_satr6_table;
            pinfo->video_acm_lut_satr7_table = stf_v3_jdi_r63452_5p2_1080p_cmd_video_acm_lut_satr7_table;
        }
        if (pinfo->gamma_support == 1)
        {
            pinfo->gamma_lut_table_R = stf_v3_jdi_r63452_5p2_1080p_cmd_gamma_lut_table_R;
            pinfo->gamma_lut_table_G = stf_v3_jdi_r63452_5p2_1080p_cmd_gamma_lut_table_G;
            pinfo->gamma_lut_table_B = stf_v3_jdi_r63452_5p2_1080p_cmd_gamma_lut_table_B;
            pinfo->gamma_lut_table_len = ARRAY_SIZE(stf_v3_jdi_r63452_5p2_1080p_cmd_gamma_lut_table_R);
            pinfo->igm_lut_table_R = stf_v3_jdi_r63452_5p2_1080p_cmd_igm_lut_table_R;
            pinfo->igm_lut_table_G = stf_v3_jdi_r63452_5p2_1080p_cmd_igm_lut_table_G;
            pinfo->igm_lut_table_B = stf_v3_jdi_r63452_5p2_1080p_cmd_igm_lut_table_B;
            pinfo->igm_lut_table_len = ARRAY_SIZE(stf_v3_jdi_r63452_5p2_1080p_cmd_igm_lut_table_R);
            pinfo->gmp_lut_table_low32bit = &stf_v3_jdi_r63452_5p2_1080p_cmd_gmp_lut_table_low32bit[0][0][0];
            pinfo->gmp_lut_table_high4bit = &stf_v3_jdi_r63452_5p2_1080p_cmd_gmp_lut_table_high4bit[0][0][0];
            pinfo->gmp_lut_table_len = ARRAY_SIZE(stf_v3_jdi_r63452_5p2_1080p_cmd_gmp_lut_table_low32bit);
            pinfo->xcc_table = stf_v3_jdi_r63452_5p2_1080p_cmd_xcc_table;
            pinfo->xcc_table_len = ARRAY_SIZE(stf_v3_jdi_r63452_5p2_1080p_cmd_xcc_table);
        }
        break;
    case STF_V3_SHARP_NT35695_5P2_1080P_CMD_PANEL:
        if (pinfo->acm_support == 1)
        {
            pinfo->acm_lut_hue_table = stf_v3_sharp_nt35695_5p2_1080p_cmd_acm_lut_hue_table;
            pinfo->acm_lut_hue_table_len = ARRAY_SIZE(stf_v3_sharp_nt35695_5p2_1080p_cmd_acm_lut_hue_table);
            pinfo->acm_lut_sata_table = stf_v3_sharp_nt35695_5p2_1080p_cmd_acm_lut_sata_table;
            pinfo->acm_lut_sata_table_len = ARRAY_SIZE(stf_v3_sharp_nt35695_5p2_1080p_cmd_acm_lut_sata_table);
            pinfo->acm_lut_satr_table = stf_v3_sharp_nt35695_5p2_1080p_cmd_acm_lut_satr_table;
            pinfo->acm_lut_satr_table_len = ARRAY_SIZE(stf_v3_sharp_nt35695_5p2_1080p_cmd_acm_lut_satr_table);
            pinfo->acm_lut_satr0_table = stf_v3_sharp_nt35695_5p2_1080p_cmd_acm_lut_satr0_table;
            pinfo->acm_lut_satr0_table_len = ARRAY_SIZE(stf_v3_sharp_nt35695_5p2_1080p_cmd_acm_lut_satr0_table);
            pinfo->acm_lut_satr1_table = stf_v3_sharp_nt35695_5p2_1080p_cmd_acm_lut_satr1_table;
            pinfo->acm_lut_satr1_table_len = ARRAY_SIZE(stf_v3_sharp_nt35695_5p2_1080p_cmd_acm_lut_satr1_table);
            pinfo->acm_lut_satr2_table = stf_v3_sharp_nt35695_5p2_1080p_cmd_acm_lut_satr2_table;
            pinfo->acm_lut_satr2_table_len = ARRAY_SIZE(stf_v3_sharp_nt35695_5p2_1080p_cmd_acm_lut_satr2_table);
            pinfo->acm_lut_satr3_table = stf_v3_sharp_nt35695_5p2_1080p_cmd_acm_lut_satr3_table;
            pinfo->acm_lut_satr3_table_len = ARRAY_SIZE(stf_v3_sharp_nt35695_5p2_1080p_cmd_acm_lut_satr3_table);
            pinfo->acm_lut_satr4_table = stf_v3_sharp_nt35695_5p2_1080p_cmd_acm_lut_satr4_table;
            pinfo->acm_lut_satr4_table_len = ARRAY_SIZE(stf_v3_sharp_nt35695_5p2_1080p_cmd_acm_lut_satr4_table);
            pinfo->acm_lut_satr5_table = stf_v3_sharp_nt35695_5p2_1080p_cmd_acm_lut_satr5_table;
            pinfo->acm_lut_satr5_table_len = ARRAY_SIZE(stf_v3_sharp_nt35695_5p2_1080p_cmd_acm_lut_satr5_table);
            pinfo->acm_lut_satr6_table = stf_v3_sharp_nt35695_5p2_1080p_cmd_acm_lut_satr6_table;
            pinfo->acm_lut_satr6_table_len = ARRAY_SIZE(stf_v3_sharp_nt35695_5p2_1080p_cmd_acm_lut_satr6_table);
            pinfo->acm_lut_satr7_table = stf_v3_sharp_nt35695_5p2_1080p_cmd_acm_lut_satr7_table;
            pinfo->acm_lut_satr7_table_len = ARRAY_SIZE(stf_v3_sharp_nt35695_5p2_1080p_cmd_acm_lut_satr7_table);
            pinfo->video_acm_lut_hue_table = stf_v3_sharp_nt35695_5p2_1080p_cmd_video_acm_lut_hue_table;
            pinfo->video_acm_lut_sata_table = stf_v3_sharp_nt35695_5p2_1080p_cmd_video_acm_lut_sata_table;
            pinfo->video_acm_lut_satr0_table = stf_v3_sharp_nt35695_5p2_1080p_cmd_video_acm_lut_satr0_table;
            pinfo->video_acm_lut_satr1_table = stf_v3_sharp_nt35695_5p2_1080p_cmd_video_acm_lut_satr1_table;
            pinfo->video_acm_lut_satr2_table = stf_v3_sharp_nt35695_5p2_1080p_cmd_video_acm_lut_satr2_table;
            pinfo->video_acm_lut_satr3_table = stf_v3_sharp_nt35695_5p2_1080p_cmd_video_acm_lut_satr3_table;
            pinfo->video_acm_lut_satr4_table = stf_v3_sharp_nt35695_5p2_1080p_cmd_video_acm_lut_satr4_table;
            pinfo->video_acm_lut_satr5_table = stf_v3_sharp_nt35695_5p2_1080p_cmd_video_acm_lut_satr5_table;
            pinfo->video_acm_lut_satr6_table = stf_v3_sharp_nt35695_5p2_1080p_cmd_video_acm_lut_satr6_table;
            pinfo->video_acm_lut_satr7_table = stf_v3_sharp_nt35695_5p2_1080p_cmd_video_acm_lut_satr7_table;
        }
        if (pinfo->gamma_support == 1)
        {
            pinfo->gamma_lut_table_R = stf_v3_sharp_nt35695_5p2_1080p_cmd_gamma_lut_table_R;
            pinfo->gamma_lut_table_G = stf_v3_sharp_nt35695_5p2_1080p_cmd_gamma_lut_table_G;
            pinfo->gamma_lut_table_B = stf_v3_sharp_nt35695_5p2_1080p_cmd_gamma_lut_table_B;
            pinfo->gamma_lut_table_len = ARRAY_SIZE(stf_v3_sharp_nt35695_5p2_1080p_cmd_gamma_lut_table_R);
            pinfo->igm_lut_table_R = stf_v3_sharp_nt35695_5p2_1080p_cmd_igm_lut_table_R;
            pinfo->igm_lut_table_G = stf_v3_sharp_nt35695_5p2_1080p_cmd_igm_lut_table_G;
            pinfo->igm_lut_table_B = stf_v3_sharp_nt35695_5p2_1080p_cmd_igm_lut_table_B;
            pinfo->igm_lut_table_len = ARRAY_SIZE(stf_v3_sharp_nt35695_5p2_1080p_cmd_igm_lut_table_R);
            pinfo->gmp_lut_table_low32bit = &stf_v3_sharp_nt35695_5p2_1080p_cmd_gmp_lut_table_low32bit[0][0][0];
            pinfo->gmp_lut_table_high4bit = &stf_v3_sharp_nt35695_5p2_1080p_cmd_gmp_lut_table_high4bit[0][0][0];
            pinfo->gmp_lut_table_len = ARRAY_SIZE(stf_v3_sharp_nt35695_5p2_1080p_cmd_gmp_lut_table_low32bit);
            pinfo->xcc_table = stf_v3_sharp_nt35695_5p2_1080p_cmd_xcc_table;
            pinfo->xcc_table_len = ARRAY_SIZE(stf_v3_sharp_nt35695_5p2_1080p_cmd_xcc_table);
        }
        break;
    case STF_V3_TIANMA_TD4310_5P2_1080P_VIDEO_PANEL:
        if (pinfo->acm_support == 1)
        {
            pinfo->acm_lut_hue_table = stf_v3_tianma_td4310_5p2_1080p_video_acm_lut_hue_table;
            pinfo->acm_lut_hue_table_len = ARRAY_SIZE(stf_v3_tianma_td4310_5p2_1080p_video_acm_lut_hue_table);
            pinfo->acm_lut_sata_table = stf_v3_tianma_td4310_5p2_1080p_video_acm_lut_sata_table;
            pinfo->acm_lut_sata_table_len = ARRAY_SIZE(stf_v3_tianma_td4310_5p2_1080p_video_acm_lut_sata_table);
            pinfo->acm_lut_satr_table = stf_v3_tianma_td4310_5p2_1080p_video_acm_lut_satr_table;
            pinfo->acm_lut_satr_table_len = ARRAY_SIZE(stf_v3_tianma_td4310_5p2_1080p_video_acm_lut_satr_table);
            pinfo->acm_lut_satr0_table = stf_v3_tianma_td4310_5p2_1080p_video_acm_lut_satr0_table;
            pinfo->acm_lut_satr0_table_len = ARRAY_SIZE(stf_v3_tianma_td4310_5p2_1080p_video_acm_lut_satr0_table);
            pinfo->acm_lut_satr1_table = stf_v3_tianma_td4310_5p2_1080p_video_acm_lut_satr1_table;
            pinfo->acm_lut_satr1_table_len = ARRAY_SIZE(stf_v3_tianma_td4310_5p2_1080p_video_acm_lut_satr1_table);
            pinfo->acm_lut_satr2_table = stf_v3_tianma_td4310_5p2_1080p_video_acm_lut_satr2_table;
            pinfo->acm_lut_satr2_table_len = ARRAY_SIZE(stf_v3_tianma_td4310_5p2_1080p_video_acm_lut_satr2_table);
            pinfo->acm_lut_satr3_table = stf_v3_tianma_td4310_5p2_1080p_video_acm_lut_satr3_table;
            pinfo->acm_lut_satr3_table_len = ARRAY_SIZE(stf_v3_tianma_td4310_5p2_1080p_video_acm_lut_satr3_table);
            pinfo->acm_lut_satr4_table = stf_v3_tianma_td4310_5p2_1080p_video_acm_lut_satr4_table;
            pinfo->acm_lut_satr4_table_len = ARRAY_SIZE(stf_v3_tianma_td4310_5p2_1080p_video_acm_lut_satr4_table);
            pinfo->acm_lut_satr5_table = stf_v3_tianma_td4310_5p2_1080p_video_acm_lut_satr5_table;
            pinfo->acm_lut_satr5_table_len = ARRAY_SIZE(stf_v3_tianma_td4310_5p2_1080p_video_acm_lut_satr5_table);
            pinfo->acm_lut_satr6_table = stf_v3_tianma_td4310_5p2_1080p_video_acm_lut_satr6_table;
            pinfo->acm_lut_satr6_table_len = ARRAY_SIZE(stf_v3_tianma_td4310_5p2_1080p_video_acm_lut_satr6_table);
            pinfo->acm_lut_satr7_table = stf_v3_tianma_td4310_5p2_1080p_video_acm_lut_satr7_table;
            pinfo->acm_lut_satr7_table_len = ARRAY_SIZE(stf_v3_tianma_td4310_5p2_1080p_video_acm_lut_satr7_table);
            pinfo->video_acm_lut_hue_table = stf_v3_tianma_td4310_5p2_1080p_video_video_acm_lut_hue_table;
            pinfo->video_acm_lut_sata_table = stf_v3_tianma_td4310_5p2_1080p_video_video_acm_lut_sata_table;
            pinfo->video_acm_lut_satr0_table = stf_v3_tianma_td4310_5p2_1080p_video_video_acm_lut_satr0_table;
            pinfo->video_acm_lut_satr1_table = stf_v3_tianma_td4310_5p2_1080p_video_video_acm_lut_satr1_table;
            pinfo->video_acm_lut_satr2_table = stf_v3_tianma_td4310_5p2_1080p_video_video_acm_lut_satr2_table;
            pinfo->video_acm_lut_satr3_table = stf_v3_tianma_td4310_5p2_1080p_video_video_acm_lut_satr3_table;
            pinfo->video_acm_lut_satr4_table = stf_v3_tianma_td4310_5p2_1080p_video_video_acm_lut_satr4_table;
            pinfo->video_acm_lut_satr5_table = stf_v3_tianma_td4310_5p2_1080p_video_video_acm_lut_satr5_table;
            pinfo->video_acm_lut_satr6_table = stf_v3_tianma_td4310_5p2_1080p_video_video_acm_lut_satr6_table;
            pinfo->video_acm_lut_satr7_table = stf_v3_tianma_td4310_5p2_1080p_video_video_acm_lut_satr7_table;
        }
        if (pinfo->gamma_support == 1)
        {
            pinfo->gamma_lut_table_R = stf_v3_tianma_td4310_5p2_1080p_video_gamma_lut_table_R;
            pinfo->gamma_lut_table_G = stf_v3_tianma_td4310_5p2_1080p_video_gamma_lut_table_G;
            pinfo->gamma_lut_table_B = stf_v3_tianma_td4310_5p2_1080p_video_gamma_lut_table_B;
            pinfo->gamma_lut_table_len = ARRAY_SIZE(stf_v3_tianma_td4310_5p2_1080p_video_gamma_lut_table_R);
            pinfo->igm_lut_table_R = stf_v3_tianma_td4310_5p2_1080p_video_igm_lut_table_R;
            pinfo->igm_lut_table_G = stf_v3_tianma_td4310_5p2_1080p_video_igm_lut_table_G;
            pinfo->igm_lut_table_B = stf_v3_tianma_td4310_5p2_1080p_video_igm_lut_table_B;
            pinfo->igm_lut_table_len = ARRAY_SIZE(stf_v3_tianma_td4310_5p2_1080p_video_igm_lut_table_R);
            pinfo->gmp_lut_table_low32bit = &stf_v3_tianma_td4310_5p2_1080p_video_gmp_lut_table_low32bit[0][0][0];
            pinfo->gmp_lut_table_high4bit = &stf_v3_tianma_td4310_5p2_1080p_video_gmp_lut_table_high4bit[0][0][0];
            pinfo->gmp_lut_table_len = ARRAY_SIZE(stf_v3_tianma_td4310_5p2_1080p_video_gmp_lut_table_low32bit);
            pinfo->xcc_table = stf_v3_tianma_td4310_5p2_1080p_video_xcc_table;
            pinfo->xcc_table_len = ARRAY_SIZE(stf_v3_tianma_td4310_5p2_1080p_video_xcc_table);
        }
        break;
    default:
        HISI_FB_INFO("Panel ID not detected %d\n", panel_id);
        break;
    }
}

static uint8_t lcdkit_panel_init(uint32_t product_id, char* compatible)
{
    uint8_t lcd_panel_id = DEFAULT_AUO_OTM1901A_5P2_1080P_VIDEO_DEFAULT_PANEL;
    int i = 0;
    int len = strlen(compatible);
    int length = 0;
    for (i = 0; i < ARRAY_SIZE(lcdkit_map); ++i) {
        length = strlen(lcdkit_map[i].panel_compatible);
        if ((lcdkit_map[i].product_id == product_id) && !strncmp(lcdkit_map[i].panel_compatible, compatible, (length > len?length:len))){
            lcd_panel_id = lcdkit_map[i].lcd_id;
            break;
        }
    }

    HISI_FB_INFO("lcd_panel_id = %d\n", lcd_panel_id);
    return lcd_panel_id;
}


#endif /*_LCDKIT_EFFECT__H_*/
